checkmarx-ltd/cx-flow

- Dockerfile
- Dockerfile-11
Update docker image to eliminate potential vulnerabilities but using minimal alpine image with updates as well as most recent Java
> Update Base Docker Image

- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/scan/ScanSteps.java
- src/test/resources/application-scan.yml
- src/test/resources/cucumber/features/integrationTests/scans.feature
skip integration tests on gradle level
also - scan tests to connect to amazone machine
> skip integration tests on gradle level

- build-11.gradle
- build.gradle
- Updating the Atlassian library to 5.2.0
- Update CX Spring boot SDK to 0.4.6 containing fix for To Verify numerical mapping
> Hotfix/atlassian 5.2.0

- src/main/java/com/checkmarx/flow/controller/TfsController.java
a new controller for TFS (previus version of ADO).
it is based on the ADO controller, but uses optionals and java 8 syntax.
> Ofer@controller for tfs

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
- src/test/resources/cucumber/features/e2eTests/githubToJira.feature
reading HOOK_NAMESPACE, HOOK_REPO , HOOK_TARGET from environment or file
> end to end test, added support for automation

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
this removes the change done by Alexey, and also removes the exception if the file is not found.
Note! I didn't add the log, since I you added logs to this file in your brunch
> fix for circle ci

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
changed the way the files are read in the end to end test, this should be compatible with windows Linux, in path and inside jars.
> change in the way resource is read

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
> another path fix

- src/test/java/com/checkmarx/flow/cucumber/integration/publishprocess/RunPublishProcessSteps.java
- src/test/java/com/checkmarx/jira/IPublishUtils.java
- src/test/java/com/checkmarx/jira/JiraTestUtils.java
- src/test/java/com/checkmarx/jira/JiraUtilsException.java
- src/test/java/com/checkmarx/jira/PublishUtils.java
Fixed create open issue.
Removed unnecessary members in RunPublishProcessSteps.java.
> Fixed project creation issues.

- sonar-project.properties
- src/test/java/com/checkmarx/flow/cucumber/component/parse/LoadingSastResultsSteps.java
this covers 4 of the 5 critical issues of soler.
> Ofer@sonar critical

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
> potential null pointer fix

- src/test/java/com/checkmarx/flow/cucumber/component/parse/LoadingSastResultsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/scan/ScanSteps.java
try with resource - 2 / 2issues bug+blocker
> Ofer@54 clean sonar cloud errors

- src/test/java/com/checkmarx/flow/cucumber/component/parse/SastResultParser.java
- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/ThresholdsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/webhook/WebHookSteps.java
sonar issues, This is also to see if sonar is back on line
> Pr ofer@sonar

- src/main/java/com/checkmarx/flow/constants/JiraConstants.java
- src/main/java/com/checkmarx/flow/utils/AesEncryptionUtils.java
- src/test/java/com/checkmarx/flow/cucumber/component/parse/SastResultParser.java
- src/test/java/com/checkmarx/jira/JiraTestUtils.java
a fix for a lot of sonar issues.
Note! the 3 bugs left open after this fix are false positives
> sonar fixes

- src/test/java/com/checkmarx/flow/cucumber/component/parse/SastResultParser.java
- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/ThresholdsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/github2jira/GitHubToJiraSteps.java
- src/test/java/com/checkmarx/jira/JiraTestUtils.java
this sould fix all sonar issues in bugs and vulnrabilities
> Pr ofer@sonar fix

- src/test/resources/cucumber/features/e2eTests/genericEndToEnd.feature
this will be the feature we will use.
it will also replace the current e2e
> added new feature file

- src/main/java/com/checkmarx/flow/config/JiraProperties.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- Azure Board 92 - JIRA search pagination, caching of custom fields on initialization
- Azure Board 93 (Client Contribution) - improved handling of error when status fails due to access.
> Jira Performance Enhancements

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/RunGenericEndToEndTest.java
- src/test/resources/cucumber/features/e2eTests/hookProperties.properties
fixed issues I found.
it is still not final version.
the generics of the feature is not working :(
> Ofer@generic e2e

- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
> fix lint issues

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
> fix lint in e2e test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Applying Issue and Pull Request Templates along with references to contribution guidelines and contribution standards.
> Adding Template/Contribution guidelines

- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerConfiguration.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerRunner.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
- src/test/resources/cucumber/features/integrationTests/cxConfigBugTracker.feature
> Udi cx config bug tracker

- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/dto/github/DeleteEvent.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
- src/test/resources/cucumber/features/componentTests/deletBranch.feature
- src/test/resources/cucumber/features/integrationTests/cxconfig.feature
> GitHub support delete branch

- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
fix for sonar issue, L925
L925
> fixed resource leak

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/config/RepoProperties.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabSecurityDasbhoard.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
This change is to add the capability of GitLab Security Dashboard as a Bug Tracker feedback option. It includes updates to properties for GitLab such as the location of the output file.
Fixes #179
Several manual end to end tests were conducted using GitLab CI. Unit Tests/Integration tests are WIP and will be included in upcoming PR.
> GitLabDashboard Support

- .circleci/config.yml
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/HookType.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
- src/test/resources/cucumber/features/e2eTests/genericEndToEnd.feature
This PR will is the base for adding pull request to the e2e tests
this is part of the e2e tests
> Pr ofer 96@e2e pr gh

- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
This is a security fix, it will bring us back to A rating
sonarcloud rule for java 3AS1444
> fixed security issue

- src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
> Fix Sonar NPE issue

- src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/PublishingSteps.java
- src/test/resources/cucumber/features/integrationTests/azure/publishing-github-flow.feature
Issues were not published to ADO in test because the list of vulnerability scanners was empty.
> Fixed: issues are not published to ADO in a test.

- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
> Fix sonar issues

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
Fix to include forcescan flag through CLI execution
Execution through CLI can now include --forcescan flag
Fixes #210 
Existing test suite provides coverage over existing flow.
> Add forcescan parameter option to CLI Execution

- .circleci/config.yml
- Dockerfile
- build-cxod.gradle
Introducing separate build for cxod implementation
Fixes #204 
Testing will be implemented within the SDK.  All existing tests are applicable for CxFlow.
> CxOD initial implementation

- src/main/java/com/checkmarx/flow/config/ServiceNowProperties.java
- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
- src/main/java/com/checkmarx/flow/dto/servicenow/Incident.java
- src/main/java/com/checkmarx/flow/dto/servicenow/Result.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/main/resources/application.yml
- src/test/java/com/checkmarx/flow/custom/ServiceNowTrackerTest.java
- src/test/resources/application.yml
> Service Now Tracker integration with CX Flow. It is integrate the Service Now Incident bug tracker flow.
> https://dev.azure.com/Checkmarx-TS/Field%20Development/_workitems/edit/27/
> Developed and tested Service Now integration using unit and integration test for testing all possible Service Now -> CX Flow scenarios, Create Incident, Update Incident, Close Incident. Tested using different projects.
> Pr ts feature/service now

- src/main/java/com/checkmarx/flow/config/ServiceNowProperties.java
- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
- src/main/java/com/checkmarx/flow/dto/servicenow/Incident.java
- src/main/java/com/checkmarx/flow/dto/servicenow/Result.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/main/resources/application.yml
- src/test/java/com/checkmarx/flow/custom/ServiceNowTrackerTest.java
- src/test/resources/application.yml
Service Now Integration with CX Flow
> Service Now Integration

- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
>Service Now Integration code improvements.
> Code refactoring, improvement

- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
Fixing Sonar Cloud issue in the Service Now Integration
> Fixing SonarCloud issue

- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/controller/TfsController.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
CxFlow should initiate scan in for default branch in case CX-FLOW-BRANCHES 
is empty
> Pr aviv scan default branch

- src/main/java/com/checkmarx/flow/bug_tracker_trigger/BugTrackerTriggerEvent.java
> Support Jira empty case to avoid entering the default section

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
> Pr nimrod@sca jira ticketing

- .circleci/config.yml
- build-cxod.gradle
Update CxOD SDK to fix SCA discrepancies introduced.
> Update CxOD SB SDK.

- src/main/java/com/checkmarx/flow/service/JiraService.java
This change is to support a new custom field of cascading select within JIRA. Implementation was completed for a customer and changes are being pulled into main code base.
Fixes #206 
Changes are minimal and non-impactful. Changes were tested with manual validation leveraging custom field of this type.
> Adding Jira custom field for cascading select

- build.gradle
Add excluded GitHub integration tests to the CircleCI flow
> Include GitHub integration tests

- .circleci/config.yml
- build.gradle
Changing the way sonar scan is executed to avoid problems with certificate on the ubuntu machine to connect to SonarCloud. This way is actually the recommended way by SonarCloud
Tested by manually running multiple builds in CircleCI and verifying that the sonar scan steps finish successfully.
> Fix sonar scan step in CircleCI 

- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GitHubApiHandler.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
I created a new helper class to interact with the GitHub API.  
This class will eventually include all the interactions with the api.  
currently it has only the push file function.
this will help us to reuse code in the testing (and in the production) 
> This is a utility extracted from the end to end tests, the tests use it so if they pass it is ok.
> created a helper for GitHub api

- src/main/java/com/checkmarx/flow/service/GitHubService.java
When scanning a private repository under an organization (not a user account) their are several failures within GitHub due to 404s and missing authentication headers within comments.
Additionally, the auto profiling logic was fixed. Some cases would cause logic to be skipped inappropriately.
Fixes #134
Leverage existing Integration / E2E testing
Manual validation of GitHub Private Repo integration (non-user organization)
> Added Ken's hot fixes to repo comments.

- .circleci/config.yml
- build-cxod.gradle
- src/main/resources/application-cxod.yml
Introducing separate build steps for CxOD (gradle and Docker).
#204
Testing will be implemented within the SDK.
All existing tests are applicable for CxFlow.
> CxOD Implementation

- src/main/java/com/checkmarx/flow/bug_tracker_trigger/BugTrackerTriggerEvent.java
- src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
- src/main/java/com/checkmarx/flow/service/BitBucketService.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
> Adds the support for merge checks available in BitBucket Server such as 1) Build Status and 2) Posting a comment or task as PR feedback after a scan is completed.
> Fixes #171
>
> …
> Pr ts feature/bb server pr feedback

- src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
- src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
- src/main/java/com/checkmarx/flow/service/BitBucketService.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
fixed top sonar issues in ScanUtils
> Ofer@sonar scanutils

- build-11.gradle
- build-cxod.gradle
- build.gradle
- src/main/resources/templates/index.html
- src/test/java/com/checkmarx/flow/cucumber/component/parse/LoadingSastResultsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/scan/ScansComponentSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GenericEndToEndSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
- src/test/java/com/checkmarx/flow/custom/JsonPropertiesTest.java
Clean OSA and SCA vulnerabilities
Tested by automatic tests by circlyCi
- documentation is irrelevant
> test end2end

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/utils/ZipUtils.java
> Fix sonar bugs

- build-11.gradle
- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/RunSCARemoteRepoSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/SCARemoteRepoScanSteps.java
Add new SCA integration tests with public & private repos
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
> Pr nimrod@add sca ci tests

- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
This is a collection of sonar fixes in the scanutils.
the biggest thing here is fixing cognitive complexity.
there are still methods not fixed.
> Pr ofer@fix sonar day

- src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
> This is a fix for issue that CxFlow found - input from http request is used as a condition in a loop.
>
> Please include any …
> Pr udi cf fix unchecked input for loop

- src/main/java/com/checkmarx/flow/dto/report/AnalyticsReport.java
- src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
- src/main/java/com/checkmarx/flow/dto/report/ScanReport.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/MergeResultEvaluatorImpl.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
- src/test/java/com/checkmarx/flow/cucumber/common/JsonLoggerTestUtils.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/GetResultsAnalyticsTestSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/RunGetResultsAnalyticsTest.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/SCARemoteRepoScanSteps.java
- src/test/resources/application.yml
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
PR - create analytics log for each SCA scan and pull reqeust
Tests: automation test is added for SCA scan, and manual tests are performed for pull request with SCA scan configuration
- All active GitHub checks for tests, formatting, and security are passing
- The correct base branch (develop) is being used
> SCA Analytics

- src/main/java/com/checkmarx/flow/dto/report/AnalyticsReport.java
- src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
- src/main/java/com/checkmarx/flow/dto/report/ScanReport.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/MergeResultEvaluatorImpl.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
- src/test/java/com/checkmarx/flow/cucumber/common/JsonLoggerTestUtils.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/GetResultsAnalyticsTestSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/RunGetResultsAnalyticsTest.java
- src/test/java/com/checkmarx/flow/cucumber/component/pullrequestanalytics/AnalyticsRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/pullrequestanalytics/AnalyticsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/SCARemoteRepoScanSteps.java
- src/test/resources/application.yml
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Reverts checkmarx-ltd/cx-flow#267
> Revert "SCA Analytics"

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
Support SCA Jira tickets aggregation
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/136?src=WorkItemMention&src-action=artifact_link
TBD
> Pr nimrod@sca jira ticketing with new aggregation logic

- src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
This commit fixes the unchecked loop condition (SAST) and some sonar issues
>
> Please include any manual steps for testing …
> Fix to Unchecked Input for Loop Condition.

- src/main/java/com/checkmarx/flow/dto/report/AnalyticsReport.java
- src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
- src/main/java/com/checkmarx/flow/dto/report/ScanReport.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/MergeResultEvaluatorImpl.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
- src/test/java/com/checkmarx/flow/cucumber/common/JsonLoggerTestUtils.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/GetResultsAnalyticsTestSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/RunGetResultsAnalyticsTest.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/SCARemoteRepoScanSteps.java
- src/test/resources/application.yml
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Tests: positive and negative SCA scan
- [ V] All active GitHub checks for tests, formatting, and security are passing
- [ V] The correct base branch is being used
> Pr orly log sca scan analytics

- src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
- src/main/java/com/checkmarx/flow/dto/report/ScanResultsReport.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
- src/test/resources/cucumber/features/componentTests/pull-request-analytics.feature
Tests:
pull request with SCA results
- [V] All active GitHub checks for tests, formatting, and security are passing
- [V] The correct base branch is being used
> Pr orly pull request sca

- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
Added tests to gradle + minor fix to tests.
None - the commit is for tests
unit/integration tests.
- [*] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [*] All active GitHub checks for tests, formatting, and security are passing
- [*] The correct base branch is being used
> Pr udi add congigascode bugtracker

- .circleci/config.yml
> add GITHUB_HOOK_REPO_SCA for e2e-tests

- .circleci/config.yml
Upload all docker images to DockerHub.
Upload all artifacts to GitHub release.
> Pr cxod8 to dockerhub

- .circleci/config.yml
Upload all docker images to DockerHub.
Upload all artifacts to GitHub release.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new …
> Pr cxod8 to dockerhub (#284)

- src/main/java/com/checkmarx/flow/dto/report/ScanResultsReport.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/GetResultsAnalyticsTestSteps.java
- src/test/resources/cucumber/features/componentTests/analytics-get-results.feature
PR - add support for get SCA results analytics
- [V] All active GitHub checks for tests, formatting, and security are passing
- [V] The correct base branch is being used
> Add tests for get results analytics for SCA

- .circleci/config.yml
remove java8 from jar name
>
> Please include any manual steps for testing end-to-end or functionality not covered by …
> remove java8 from jar name

- src/main/java/com/checkmarx/flow/service/JiraService.java
> Revert: Fix to Unchecked Input for Loop Condition. (#277)

- build-11.gradle
- build-cxod.gradle
- build.gradle
update cxflow version to 1.6.1
All automation End to End and Integration tests passed
> update cxflow version to 1.6.1

- src/main/java/com/checkmarx/flow/service/JiraService.java
> Update SCA Jira tickets content with final remarks

- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersStepsRunner.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/scans/RunSCARemoteRepoSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/scans/SCARemoteRepoScanSteps.java
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Add new SCA filtering configuration, both for score and by severity
Added 8 integration tests to tests main filters metrics
> Pr nimrod@sca filters

- src/main/java/com/checkmarx/flow/custom/GitHubIssueCommentFormatter.java
fix typo on github - 'issue still exist' comment
Typo/Wording on "Issue Still Exist" Github comment. #279
All integration tests and End to End tests passed successfully
Manual tests done to verify new wording
> fix typo on issue-still-exist github issue

- .circleci/config.yml
> add algorithm to run nightly on 4am an delete old namespaces from eks
>
> Please include any manual steps for testing end-to-end …
> pr-nightly-clean-eks

- src/main/java/com/checkmarx/flow/aop/LoggingAop.java
Fixed - MDC unique value not passed to result process flow
All integration tests and E2E passed
verifying with manual tests for
1. webhook floe with SAST scan and open tickets
2. webhook floe with SCA scan and open tickets
> Add MDC value to result flow

- src/main/java/com/checkmarx/flow/config/ADOProperties.java
- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
Fix bug https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/159
> Fix Ado update issue with specified project name

- src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
- src/main/java/com/checkmarx/flow/custom/ImmutableIssueTracker.java
- src/main/java/com/checkmarx/flow/service/FilenameFormatter.java
Additional fix for the Absolute_Path_Traversal vulnerability: support for paths in GitLabSecurityDashboard instead of just filenames. 
Fixed a typo in class name.
> Support for paths in GitLabSecurityDashboard

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
…lse-positive by viewing the filtered summary
Fix to consider filtered and not exploitable issues during the break build logic for CLI execution.
Fixes #311 
Local tests matching the referenced issue were conducted.
> CLI break build fix

- build-11.gradle
- build-cxgo.gradle
- build.gradle
Update Cxflow version to 1.6.2
All end to end and integration tests pass succesfully
> update version to 1.6.2

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
Fixes #311 
Local tests matching the referenced issue were conducted.
> Pr ts hotfix/cli break build

- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
- src/test/resources/cucumber/features/componentTests/thresholds.feature
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/186
> Pr nimrod bug186

- build-11.gradle
- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/scans/RunSCARemoteRepoSteps.java
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/166
> Pr nimrod 166 improve sca tests duration

- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/publishprocess/RunPublishProcessSteps.java
> Pr fix jira integration tests

- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeRunner.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
- src/test/resources/cucumber/features/integrationTests/cxconfig.feature
> SCA config-as-code integration test
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/95
> Add new integration test for SCA config as code

- src/main/java/com/checkmarx/flow/service/JiraService.java
> Adds support for new field of type VersionPicker in Jira.
> #338 
> Manual Testing done using private Jira instance.
> Added support for VersionPicker field in Jira.

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/GitLabProperties.java
This PR enables GITLABMERGE as a bug-tracker implementation through CLI.  It requires --project-id to be provided, which is an env variable available in the GitLab CI pipeline/job.
Manual testing conducted with GitLab CI.
> GitLab CLI Merge Feedback

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Added releaseDrafter github action to automatically generate release
> Added releaseDrafter github action to automatically generate release

- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
- src/test/resources/cucumber/features/integrationTests/cxconfig.feature
> Credentials validation removed from SCA cx-config test

- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
> This pr is created to fix a failing test case due to NPE.
> Fix for component tests to avoid NPE in sastPR/ThresholdSteps

- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
- src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/PublishingStepsBase.java
- src/test/resources/cucumber/features/integrationTests/azure/github2ado/github2ado.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Fixed: CxFlow open Azure issues in dynamic project name and namespace, based on Azure webhook payload
> Pr fix ado dynamic project and namespace

- build-11.gradle
- build-cxgo.gradle
- build.gradle
The purpose of this PR is to update release version to 1.6.3, and to clean the gradle file
All E2E and integration tests pass successfully
To confirm the gradle code changes - same tests are executed before and after this change
> update cxflow version 1.6.3

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/GitLabProperties.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
- src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java
This PR is to introduce the option for SCA scanning through CLI/Batch execution.  The default scanner is sast if nothing is provided, otherwise the CLI execution will honor the enabled scanners from the configuration (sca/sast)
Manual testing has been conducted to validate execution of both SAST/SCA when the vulnerability scanners are specified in the configuration.
> SCA Local Source Scanning (Zip Upload) via CLI/Batch

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/publishprocess/RunPublishProcessSteps.java
- src/test/java/com/checkmarx/jira/IJiraTestUtils.java
- src/test/java/com/checkmarx/jira/JiraTestUtils.java
- src/test/resources/cucumber/features/integrationTests/jira/publish-processing.feature
> Adding a Bug-Tracker's issue a new 'recommended fix' link
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/193
Added a new validation test for checking the link do exists on an issue's body
> Added new recommended fix link to Bug tracker's issues

- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
- src/test/java/com/checkmarx/flow/utils/ScanUtilsTest.java
- src/test/resources/cucumber/features/e2eTests/genericEndToEnd.feature
> A partial fix for Bug-201: Set vulnerability scanners to scanRequest instead of the FlowProperties
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/201
> Added Partial Fix for bug-201: vulnerability scanners are part of scanRequest

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersSteps.java
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Pr nimrod sca filters tests new repo

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
minor fixes - code review AST branch by Alexey
> fixes - ast review by Alexey

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
- src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java
- src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java
This a refactoring of recent changes in implementing classes of VulnerabilityScanners,
This is done to decuple the scanners from the flow, important for scanCli etc...
USER STORY 192: https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/192
passed all current tests.
we are adding new tests to cover the sca cli.
- [ v] All active GitHub checks for tests, formatting, and security are passing
- [ v] The correct base branch is …
> moved functionality to vulnerabilityScanner

- .circleci/config.yml
- build.gradle
- src/main/java/com/checkmarx/flow/constants/SCATicketingConstants.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/IntegrationTestContext.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliStepsRunner.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliStepsRunner.java
- src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Support SCA new scans from CLI
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/192
New integration tests were added, checking SCA scans is being initiated by CLI.
Another tests regarding filtering enablement will be added later on
> Pr us 192 cli tests

- src/main/java/com/checkmarx/flow/controller/GitLabController.java
> NPE fix for DDos attack for GitLab request webhook event trigger
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/204
> Fixed: NPE fix for potential DDos attack

- .circleci/config.yml
> remove test namespace from clean-eks job

- src/main/java/com/checkmarx/flow/service/JiraService.java
the getIssues function used a loop that potentially could be endless.
this refactoring fixes that issue, the code is shorter and is more readable.
[user story 145](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/145/)
> fixd variant and invariant of getIssues

- .circleci/config.yml
Add end-to-end test logs to circleci
> get cxflow logs to end to end tests

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/ASTScanner.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/AstCommonSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/RunAstRemoteRepoSteps.java
- src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
PR support AST results
Tests: happy flow and negative tests (expired token and incorrect machine name)
> Pr orly support ast results

- .circleci/config.yml
> add k8s external secret per deployment

- .circleci/config.yml
- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/bugtrackers/jira/AstTicketsCreationViaJiraSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/bugtrackers/jira/RunAstTicketsCreationViaJiraSteps.java
- src/test/resources/cucumber/data/sample-ast-results/5-findings-2-high-3-medium.json
- src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/152
The test is simulating a new AST scan and check for corresponding tickets JIRA
> Added new AST Jira Integration test

- src/main/java/com/checkmarx/flow/service/BitBucketService.java
- src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
> This fixes the issue #360 by adding feedback for PR when there's an active scan running in checkmarx for the same project.
This would update the PR status accordingly and also post a comment for the same. This works for all the repos.
> #360 
> Manual testing done by keeping the scan-resubmit flag set to false.
> Fix for Issue #360 : Added PR feedback in case of existing active scan.

- src/test/java/com/checkmarx/flow/cucumber/component/ast/parse/GitHubCommentsASTSteps.java
fix test AST comments - prevent method endBlockMerge
> fix test AST comments - prevent method endBlockMerge

- src/main/java/com/checkmarx/flow/config/ScmConfigOverrider.java
>A minor fix to a case an optional instance' value is not defined 
> In case optional instance value are not defined - throw an exception

- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/PublishTicketsWithOptionalScmConfSteps.java
> Fixing GitHub integration tests
> Pr nimrod fix unstable GitHub tests

- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
- src/main/java/com/checkmarx/flow/dto/azure/Content.java
- src/main/java/com/checkmarx/flow/dto/azure/Value.java
- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/utils/ADOUtils.java
- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
> This PR adds the support for 'Config as Code' and 'Auto Profiling' in AzureDevOps repositories.
> #148 & #149 
> Manual Testing done using internal ADO.
> Azure DevOps : Support for Config-as-code and Auto Profiling.

- src/main/java/com/checkmarx/flow/service/ADOService.java
> This PR will help remove the existing duplicate code (Major) issue from Sonar.
> Manual Testing
> Code changes to avoid duplicate code warning in Sonar

- src/main/java/com/checkmarx/flow/service/JiraService.java
When the Jira project was not accessible or did not exist, the system would have thrown a NoSuchElementException.
now there are better logs, and a IllegalArgumentException with "The Jira project " + jiraProject + " is not accessible" in the cause. 
case - 00056687
> refactoring JiraService custom fields

- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
purpose of this pull request is to add more tests to work with sca through command line:
- add tests for scan with filters
- add tests for get-latest-project-results with filters
> add sca latestProjectResults filters tests

- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
> Fixed -  Sonar potential NPE on ServiceNowTracker

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
the class htmlhelper used StringBuilder to create messages, it had too many .append() calls to be readable.
this change is basically, creating some simple functions to do batch-append.
this is just a refacturing
> Pr ofer@code cleanup

- src/main/java/com/checkmarx/flow/config/RepoProperties.java
- src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java
#376 
> New PR comments summary design is implemented for all supported scanners (SAST, SCA & AST)
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/233
> Added new PR comments summary design

- src/main/java/com/checkmarx/flow/service/JiraService.java
change exception log to give clearer message when Jira properties not provided correctly
TS ticket: https://checkmarx.sharepoint.com/:li:/s/SFDCLightningReportingPlatform/E-_rJa-zxPdOjK0Sl6xA5IcBGqMwkDv2LpomPh7HnZOpUA?e=E0oVmq
BUG 247: https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/247
> fix exception log in jira service

- build.gradle
- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/ImmutableIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/ScaCsvParameters.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/JAXBHelper.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
> Support SCA results with local files bug-trackers reports (JSON, XML & CSV)
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/206
> Publish SCA results into local files

- src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
fix jira project name - which clashes with other porject in CI
> Pr orly fix jira test project

- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Update SCA tests with new expected results
- [X ] All active GitHub checks for tests, formatting, and security are passing
- [X ] The correct base branch is being used
> Update SCA tests with new expected results

- build-cxgo.gradle
- Updating CxGo SDK to Leverage LTD sonatype group id.
- com.github.checkmarx-ltd
- Update to version 0.1.38 of CxGo SDK which includes leveraging the published CxGo APIs for result processing
- Includes SCA results
Integration tests are conducted as part of CxGo SDK release
> Update CxGo SDK to version 0.1.38

- README.md
> Added badges and link to wiki

- src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
> Fix issue on merge requests with info severity results
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/286
> Related to GitHub Issue: #436
> Fixed Bug-286: Issue on merge requests with info severity results

- build-11.gradle
- build.gradle
> Switch cx-spring-boot-sdk ts dependency to ltd
> Switch cx-spring-boot-sdk ts dependency to ltd

- .circleci/config.yml
orb circleci/aws-eks@0.2.6 had upgraded to circleci/aws-eks@1.0.0
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and …
> orb circleci/aws-eks had upgraded

- src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
Fix nullPointerException when cxflow trying to write mitreUrl, and property not exist
gh issue #416
manual
> add mitre-url nullPointerException validations

- .circleci/config.yml
- .github/release-drafter.yml
- build-11.gradle
- build-cxgo.gradle
- build.gradle
Added publishing artifacts to github pre-release on each successful pipeline on Develop branch
Manual CircleCI pipeline tests
> Pr natalie prerelease

- build-11.gradle
- build-cxgo.gradle
- build.gradle
> Update config-provider with new version: 1.0.9
> Update config-provider with new version: 1.0.9

- .circleci/config.yml
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Added publishing artifacts to github pre-release on each successful pipeline on Develop branch
Modified Release drafter to publish release notes to draft (and temporary disabling it on the repo level manually)
Manual on private branches
> Added publishing artifacts to github pre-release on each successful pipeline on Develop branch

- src/main/java/com/checkmarx/flow/controller/GitLabController.java
Fix gitlab config as code
issue #448
manual tests with private and public projects
> fix repo project ID set for scan request

- build.gradle
- helm/cxflow/templates/external-secret.yaml
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
- src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
- src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
> Enable AST CLI & Remote Env tests
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/290
> Enable AST CLI & Remote Env tests

- .circleci/config.yml
Rename create github release step in CircleCI and change upload release/prerelease to deleting the previous artifacts
Manual on local branch
> Change pre-release artifacts generation options

- src/main/java/com/checkmarx/flow/controller/GitHubController.java
Adding logic to skip push event caused by delete event from GitHub.
Some unused imports were also removed.
Fixes #463 
Manual testing and existing pipeline are applicable
> Adding logic to skip push event caused by delete event from GitHub

- .circleci/config.yml
> use latest authenticator-release

- build.gradle
Fix SCA findings aggregation logic - showing inconsistent output results
dev.azure.com/CxFlow/CxFlow/_workitems/edit/309
wiki: https://github.com/checkmarx-ltd/cx-flow/wiki/CxGO--(from-1.6.12)
manual tests to validate the SCA and SAST tickets logic
> update cx-sdk version to fix SCA issues  logic

- .github/workflows/release-drafter.yml
Fix release drafter to ignore prereleases. Had to fork the release-drafter and point to use github action that I created from the fork.
Manually on private branch
> Fix release drafter to ignore prereleases

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
> Add 'Training' ticket markdown link
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/310
> Fixed - Add 'Training' ticket markdown link

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
- src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
- src/test/resources/cucumber/data/sample-ast-results/5-findings-2-high-3-medium.json
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
Fix bug 474 - Json typo
Typo in results JSON produced by CxFlow REST API #474
> Pr asaf fix bug 474

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
> fix null pointer exception when SCA version is null (#516)

- helm/cxflow/templates/external-secret.yaml
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
> add cxflow/cxgo secrets

- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
> Fix for bug #508 where Cxflow was closing the non-checkmarx issues in Gitlab since the condition for checking issue title was missing.
> #508 
> Manual Testing done.
> Bugfix #508 : Added the missing check to determine if the issue title start with 'Cx'

- docs/Execution.md
- docs/Labs.md
Updated Labs.md for better readability.  
Corrected docker location in execution.md
N/A
N/A
N/A
> Updated & Streamlined Labs

- .circleci/config.yml
> Pr remove internal secrets

- .circleci/config.yml
- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/service/JiraService.java
> Supports the recent Jira changes where the user's name is no longer used as assignee value for Jira ticket. Instead, an accountId belonging to the user will be used to specify the assignee for any Jira ticket.
> #499 
> Manual Testing done
> Bug #499 : Fix for Jira ticket assignee.

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Cx-Flow SCA vulnerabilities fix 
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/326
> Fix Cx-Flow SCA vulnerabilities

- src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
Fixes parsing of GitHub App private key files with CR or CRLF line endings.
#537 
1. Create a GitHub App
2. Generate a private key for the app
3. Convert the key file to PKCS#8 format
4. Change the key file's line endings (if necessary) to CRLF
5. Configure the github.app-id and github.app-key-file properties for CxFlow accordingly
6. Start CxFlow and note that the app starts successfully
7. Repeat steps with 1-6 but in step 4 change line endings to LF, and observe that app still launches successfully as expected
> fix parsing GitHub App private key with CR and CRLF line endings (#537)

- src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
…7) (#538)
Please refer to #538 
Fixes #537
> Fix GitHub App private key parsing 

- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java
Fix AST integration tests after host url changed
moving AST host property to circleci environment variables
> fix ast integration tests

- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
> This PR fixes an NPE which was occurring when Sarif was set as Bugtracker and scan/scan results are from CxGo.
> No bug was logged since the issue was fixed immediately after it was discovered.
> Manual testing done.
> Fixed an NPE occurring while generating Sarif report from CxGo scan.

- docs/Work-with-external-scripts.md
Fix comments-script configuration example
comments script should be configured under **cx-flow** section
Fix #547
> fix comments-script config example

- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/main/java/com/checkmarx/flow/service/GitAuthUrlGenerator.java
- src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
- src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Fix SAST vulnerabilities

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
> Support Cx-Go scans with over GitLab with Cx-Integrations
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/341
> Support Cx-Go scans with over GitLab with Cx-Integrations

- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
- src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
- src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature
Fix bug: BUG 334 - CxFlow doesn't block pull request merge on AST\SCA scans
[Block pull request](https://github.com/checkmarx-ltd/cx-flow/wiki/Thresholds-and-policies#blockPullRequest)
> fix merge block for ast

- docs/WebHook-Registration.md
- src/main/java/com/checkmarx/flow/config/GitHubProperties.java
- src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
…rt for GH Enterprise < 2.22
Externalize property for headers for GitHub App support  
Add Support for version before 2.22 has 
Fixes #554 
Manual GitHub App testing completed
> Add GitHub App Support for GH Enterprise < 2.22

- docs/Configuration.md
- docs/Troubleshooting.md
- src/main/java/com/checkmarx/flow/service/JiraService.java
After input from TS, the following improvements were added:
- Better error logging for Jira's 'load custom fields' flow.
- Wiki: Jira configuration
- Wiki: Configuring logs for troubleshooting.
> Logging and Wiki improvements

- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/ServiceNowTracker.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
- src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
> Fixed bug #574: SCA do not follow-up when creating an issue
> #574 
TBD
> Fixed bug #574: SCA do not follow-up when creating an issue

- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
> Support Cx-Flow : Cx-Integrations E2E flow. Convert Cx-flow 'ADO' SCM name to 'azure' with Repos-Manager's terminology
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/342
> Support Cx-Flow : Cx-Integrations E2E flow

- src/main/java/com/checkmarx/flow/config/external/CxGoConfigFromWebService.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
> Align cx-go integrations DTO with new name
> Align cx-go integrations DTO with new name

- src/main/java/com/checkmarx/flow/service/GitHubService.java
Fix Bug 560 - Branch name extraction
https://github.com/checkmarx-ltd/cx-flow/issues/560
> Fix bug #560 - Branch name extraction

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
- src/main/java/com/checkmarx/flow/controller/FlowController.java
- src/main/java/com/checkmarx/flow/controller/TfsController.java
- src/main/java/com/checkmarx/flow/controller/WebhookController.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/main/java/com/checkmarx/flow/service/EmailService.java
- src/main/java/com/checkmarx/flow/service/FilterFactory.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
> Support BitBucket E2E flow with Cx-Integrations
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/343
> Performed manual e2e testing
> Support BitBucket E2E flow with Cx-Integrations

- docs/Configuration.md
- docs/Excluding-Files-from-Zip-Archive.md
The zip-exclude option has been here for a while but isn't documented yet. The current PR fixes this gap.
>  Added documentation for the cx-flow.zip-exclude option

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
Fix GitLab merge request use case when namespace or repoName not provided
GitLab merge request manual tests
GitLab automation tests
> fix git lab merge git url scan

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
> Fix SCA direct libraries vulnerabilities
> Fix SCA direct libraries vulnerabilities

- .circleci/config.yml
- build-11.gradle
- build-cxgo.gradle
- build.gradle
- docs/Work-with-external-scripts.md
- src/main/java/com/checkmarx/flow/config/JiraProperties.java
- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/resources/application-full.yml
- src/main/resources/application.yml
- src/main/resources/samples/JiraProjectKey.groovy
- src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
- src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
- src/test/java/com/checkmarx/flow/service/HelperServiceTest.java
- src/test/resources/application.yml
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
(Optional) Determine JIRA project key by given script
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/365
> Pr asaf jira script

- src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Avoid race condition - add wait for operation - pull request not pending
> Avoid race condition - add wait for pull request status not pending

- build-11.gradle
- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
- src/test/resources/cucumber/features/integrationTests/ast/astScanProcessing.feature
- src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature
> change sdk version to 68 - support AST authorization for local sources scan

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptSteps.java
- src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/invalid-return-type-project-key-script.groovy
- src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/invalid-syntax-project-key-script.groovy
- src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/jira-standard-project-key.groovy
- src/test/resources/cucumber/data/input-scripts-sample/jira-project-key/parse-jira-project-key.groovy
- src/test/resources/cucumber/features/componentTests/configure-jira-project-key-script.feature
Add tests to a new feature - Determine JIRA project key script 
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/365
> Pr asaf jira script new

- src/main/java/com/checkmarx/flow/constants/SCATicketingConstants.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/ado/ScaIssuesCreationSteps.java
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Remove SCA severity & score detail from ticket key & title 
> [Feature Url](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/490)
Manual tests were performed
> Remove SCA severity & score detail from ticket key & title 

- docs/Configuration.md
It is unclear by the currrent documentation on the format of exclude-folders and exclude-files.  It should be one string and comma separated.  Current users were trying to exclude files & folders comma separated with multiple strings.
N/A
Tested the format of the table.
> Update exclude documentation

- src/main/resources/application-sca.yml
- src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
- src/test/resources/application-sca.yml
- src/test/resources/cucumber/data/input-files-toscan/cx.config.src
> Update SCA apiUrl domain
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/373)
> Update SCA apiUrl domain

- docs/Labs.md
> This PR corrects the broken links for the sample files from Wiki's Labs Page.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
> Corrected the broken file links for Wiki.

- src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Fix CxGo automation - creates new commit in github project
> fix cxgo tests

- build-11.gradle
- build.gradle
> Upgrade SDK version to 0.4.75: Fix NPE in filterValidator
#620 
> [Bug](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/503)
> Upgrade SDK version to 0.4.75: Fix NPE in filterValidator

- docs/Integration-with-CxSCA.md
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
> SCA project team assignment test & WIKI minor amendments
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/495)
> SCA project team assignment test & WIKI minor amendments

- build-11.gradle
- build.gradle
> Upgrade SDK version - fix SCA vulnerabilities
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/512)
> Upgrade SDK version - fix SCA vulnerabilities

- build-11.gradle
- build-cxgo.gradle
- build.gradle
> Fix SCA vulnerabilities.
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/512)
> Fix SCA vulnerabilities

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
fix Cli mode - Support Gitlab CRUD actions on notes
> Pr asaf fix cli gitlab notes

- src/main/java/com/checkmarx/flow/service/GitLabService.java
Following James email, Gitlab repo comment creation we now use a generic parser to handle different time-zone formats.
> Fix Gitlab Date parser issue

- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Remove unused product from scan request
> Remove unused product from scan request

- docs/Thresholds-and-policies.md
> Grammar fixes in the 'Thresholds' wiki page

- build-11.gradle
- build.gradle
>This PR will help to enable the proxy support for SCA by incrementing the SDK version that contains the related code change.
> Manual Testing done using WinGate.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
> Updated the SDK version to 0.4.94

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/constants/FlowConstants.java
- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
Needed to add merge id in request metadata in order to update an existing comment
https://github.com/checkmarx-ltd/cx-flow/issues/655
> Fix merge comment - CLI mode

- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Fix Gitlab merge-request comments tests
> fix gitlab comments integration tests

- src/main/resources/application.yml
> Removed Jira as the default bugtracker from the default application.yml since it was causing an exception in some scenarios.
> Manual Testing
> Removed Jira as the default bug tracker

- build-11.gradle
- build.gradle
> Upgrade SDK version to 0.4.95
> Upgrade SDK version to 0.4.95

- build-11.gradle
- build-cxgo.gradle
- build.gradle
- docs/Proxy-and-HTTPS-Configuration.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
> This PR adds support for using https proxy while triggering sca scans. It also adds a new command line parameter 'trust-cert' to enable the trusting of self signed certificates.
> Manual Testing done using squid proxy.
> Added support for using HTTPS proxy with SCA.

- build-11.gradle
- build.gradle
> Upgrade SDK version to 0.4.97
> Upgrade SDK version to 0.4.97

- .circleci/config.yml
> remove AST integrarion tests

- src/main/java/com/checkmarx/flow/custom/ImmutableIssueTracker.java
- src/main/java/com/checkmarx/flow/service/IssueService.java
- src/test/java/com/checkmarx/flow/cucumber/component/csvissuetracker/CsvIssueTrackerRunner.java
- src/test/java/com/checkmarx/flow/cucumber/component/csvissuetracker/CsvIssueTrackerSteps.java
- src/test/resources/cucumber/features/componentTests/csv-issue-tracker.feature
> Fix bug - sast which for .csv reports misses some vulnerabilities
> https://checkmarx.lightning.force.com/lightning/r/Case/5004K000006sxhlQAA/view
https://checkmarx.atlassian.net/browse/AST-1674
> fix bug - sast results to csv

- src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/ImmutableIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/WebPostIssueTracker.java
- src/main/java/com/checkmarx/flow/service/ExternalScriptService.java
- src/main/java/com/checkmarx/flow/service/IssueService.java
Fix SAST vulnerabilities in Cx-Flow
https://checkmarx.atlassian.net/browse/AST-1838
> Saras fix vulnerabilities

- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Added commit hash for GitLab webhook events
[AST-1824](https://checkmarx.atlassian.net/browse/AST-1824)
Similar issue for GitHub: https://checkmarx.atlassian.net/browse/AST-352
Done manually.
> Added commit hash for GitLab webhook events

- build-11.gradle
- build.gradle
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
> Support conditionGroups when creating a new SCA policy
> Support conditionGroups when creating a new SCA policy

- src/main/java/com/checkmarx/flow/service/HelperService.java
> fix - trigger scan also if the branches  list is empty
> [User Story](https://checkmarx.atlassian.net/browse/AST-2821)
> AST-2821 Fix - trigger scan also if branch list is empty

- src/main/java/com/checkmarx/flow/service/IastService.java
- src/main/java/com/checkmarx/flow/service/IastServiceRequests.java
> remove required iast property block

- src/main/java/com/checkmarx/flow/service/JiraService.java
> SCA Jira tickets severity do not match the priority
> [Bug URL](https://checkmarx.atlassian.net/browse/AST-2428)
> Fix #767
> AST-2428 - SCA Jira tickets severity do not match the priority

- docs/Tutorials.md
> Add CxIAST Tutorial

- templates/gitlab/v3/Checkmarx.gitlab-ci.yml
This new template file does three things:
1. Adds GITLAB_URL and GITLAB_API_URL for overwriting
2. Removes hardcoded default branch (master)
3. Adds new flag and step to publish to Security Dashboard on MRs
N/A
Manual tests and user approaval.
> New template file to handle GITLAB_URL, dashboard on MR and removed hardcoded default branch

- .circleci/config.yml
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/ScanResultsBuilder.java
- src/test/resources/cucumber/features/componentTests/analytics-get-results.feature
- src/test/resources/cucumber/features/componentTests/astComments.feature
- src/test/resources/cucumber/features/componentTests/csv-issue-tracker.feature
Add ssh support for new projects
All automation and E2E tests pass
> Add ssh support for new projects

- src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
- src/main/java/com/checkmarx/flow/dto/bitbucketserver/Author.java
- src/main/java/com/checkmarx/flow/dto/bitbucketserver/FromRef.java
- src/main/java/com/checkmarx/flow/dto/bitbucketserver/Links.java
- src/main/java/com/checkmarx/flow/dto/bitbucketserver/ToRef.java
- src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerMergeHandler.java
> This PR solves the issue where Bitbucket's new payload for a PR event was not being consumed.
> Fix for bitbucket PR webhook broken

- Release.txt
- docs/Configuration.md
- docs/CxSCA-Integration.md
> GitHub Action exclude folder & exclude files are not working.
> https://github.com/checkmarx-ltd/cx-flow/issues/658
> --exclude-folders=”model,modeltest”
above format works for excluding folders
> exclude-folders works without trailing /. So updated Configuration.md file

- src/main/java/com/checkmarx/flow/service/FlowService.java
> This PR fixes the issue of SAST scan not executing if SCA scan fails when both the vulnerability scanners are enabled.
> fix for sast scan not executing when sca scan fails

- docs/AWS-Fargate-Deployment.md
- docs/Configuration.md
- docs/CxSAST-Version-9.0.md
- docs/Execution.md
- docs/YML-Example-Files.md
> Updated documentation for alt-project, jira label-prefix and protected branches.
- [] All active GitHub checks for tests, formatting, and security are passing
> Documentation update for alt-project, protected branches and jira label-prefix

- build-11.gradle
- build.gradle
sdk update to support sca branch scanning …
> sdk update to support sca branch scanning

- README.md
- docs/Configuration.md
- docs/CxSAST-Version-9.0.md
- docs/Tutorials.md
- docs/YML-Example-Files.md
- src/main/resources/application-9.0.yml
- src/main/resources/application-full.yml
This pull request updates the CxFlow documentation:
- Examples of specifying a log file have been corrected.
- The checkmarx.settings-override parameter is now documented.
Addresses https://github.com/checkmarx-ltd/cx-flow/issues/775
Not applicable: this PR does not include any code changes.
> PR Documentation Fixes

- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/Configuration.md
- docs/YML-Example-Files.md
- src/main/java/com/checkmarx/flow/service/JiraService.java
>This PR add warning log for jira-field-name when set to Labels and contains documentation update.
> Added warning log for jira-field-name when set to Labels

- src/main/java/com/checkmarx/flow/service/IastService.java
fix NullPointerException when we create a task in githab/gitlab/azure
>
> Please include any manual steps for testing end-to-end …
> small changes in Cx-flow iast integration.

- build-11.gradle
- build.gradle
- docs/Configuration.md
- docs/CxSAST-Version-9.0.md
- docs/YML-Example-Files.md
- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
> This PR adds feature that will allow to create a branched project from base project. When a event request is generated from a branch of a project if the new cx-branch property is set to true will create a branched project and not a new normal project in SAST.
When   CurrentBranch (master) = DefaultBranch (master)     cx-branch = true | When CurrentBranch   (branch-for-test) != DefaultBranch (master)     cx-branch = true …
> added feature to support branched project from base project

- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
- src/main/java/com/checkmarx/flow/utils/ScanUtils.java
> This PR fixes the issue of / not present in the RepoUrl and also fixes issues of the defaultBranch in CxParams being set as null.
Created a PR from ADO and project was created as well as "/"  was added to the end of RepoUrl.
- [] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate …
> fix slash not present in repoUrl and issues with branched project

- src/main/java/com/checkmarx/flow/config/JiraProperties.java
add more automatically statuses for jira.  …
> add more automatically statuses for jira

- Dockerfile
- src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
> ADO CRLF update

- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
> This PR fixes the regression with creating branched project.
Tests:
1. ScanLocal Repo from CLI.
2. PUSH and PULL Events on ADO and GitHub.
- [] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
> fixed branched project regression

- README.md
- src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java
> This PR contains documentation changes along with comment on BitBucketServerController.
> documentation update along with comments

- build-11.gradle
- build.gradle
- docs/Configuration.md
- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/controller/WebhookController.java
- src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
- src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsCommandLineCommonSteps.java
> This PR adds feature to override thresholds via webhook parameter and also uptakes the version of log4j to 2.17.1 and also changes url of JIRA instance for test cases.
GITHUB-PULL     Webhook URL:   url?threshold-high=12&threshold-medium=10&threshold-low=20     SAST Scan High Vuln Count : 71     SAST Scan Medium Vuln Count : 72     SAST Scan Low Vuln Count : 352 | GITHUB-PULL     Webhook URL: …
> Feature to provide thresholds via Webhook and log4j version uptake to 2.17.1

- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Feature 2. links + attack vector (captured in this FR)(Refer to CodeQL "Show Path" Link)
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added …
> [ADO:587] CxFlow: GH Action Updates - links and attack vector

- src/main/java/com/checkmarx/flow/config/SarifProperties.java
- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
https://github.com/checkmarx-ltd/cx-flow/pull/832
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests …
> Add Security Severity Attribute in Report of SARIF File

- docs/Configuration.md
- docs/CxConfigProvider.md
- docs/Home.md
> Wiki redesign

- src/main/java/com/checkmarx/flow/controller/FlowController.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsCommandLineCommonSteps.java
> Shard report fix

- Dockerfile
Reverted dockerfile changes to original state.
Tested docker image in LocalScan mode, Web mode for Girhub,ADO and batch mode.
> reverted dockerfile changes to original

- Dockerfile
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Uptake version of alpine in dockerfile
> Tested LocalScan, Azure PULL/PUSH and GITHUB PULL/PUSH in --web mode, --batch mode
> uptake alpine version to 3.15 and Java11 version to 11.0.14_p9-r0

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/test/resources/cucumber/features/componentTests/filter-script.feature
This PR fixes the vulnerabilities present in CxFlow.
Tested cxflow in --web mode (ADO,GitHub), docker, and localScan.
> Fixed CxFlow Vulnerabilities

- docs/Configuration.md
> Documentation update for post-action-postback-id and settings-override

- docs/Configuration.md
> This PR updates branched project documentation
> Branch project documentation update

- build-11.gradle
- build.gradle
> This PR fixes the fasterxml vulnerabilities
> Tested CxFlow in --web(Github,ADO), --project, LocalScan modes
> Fixed fasterxml related vulnerabilities

- build-11.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> This PR upgrades the spring boot version to 2.6.1
> Tested with --localScan mode, --batch mode, --project mode, --web mode(Github,ADO), docker
> Upgrade spring boot version to 2.6.1

- docs/Config-As-Code.md
- docs/Configuration.md
- src/main/java/com/checkmarx/flow/dto/FlowOverride.java
Fix config as code examples.
N/A
N/A
> Wiki config as code fixes

- src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
>This PR provides feature to handle PR update event of BitBucket Cloud.
> When created a PR the enabled vulnerability scanners started scanning the code and added a comment on the PR, when the same PR was updated instead of giving 403 the scans were again started and comments were updated on the PR with latest result.
- [] I have added documentation for new/changed functionality in this PR (if applicable).  *If …
> Feature to support bitbucket PR update event

- build-11.gradle
- build.gradle
- docs/AWS-Fargate-Deployment.md
- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/CxSCA-Integration.md
- docs/YML-Example-Files.md
- src/main/java/com/checkmarx/flow/service/JiraService.java
> This PR provides feature to map CxSCA results to JIRA issues similar to cx,static,results.
> Created JIRA custom fields for SCA results and scanned Project in CxFlow with scanner as SCA and bug-tracker as JIRA and appropriate SCA results were mapped to their corresponding Jira Custom fields.
> Pr provide custom fields in jira for sca

- src/main/java/com/checkmarx/flow/config/SonarQubeProperties.java
- src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
CxFlow will generate the report as for the format of sonarqube generic issue import format.
Below is the configuration for application.yml SonarQube:
```
cx-flow:
bug-tracker: SonarQube
bug-tracker-impl:
- SonarQube
```
```
sonarqube:
file-path: {FILE_PATH}
```
This will generate SonarQube Issue Report for CxFlow SAST Scan.
1. Set Sonar Scanner in Windows PATH Varaible. …
> [SAST Scan] Provide support for Generic Issue Format of Sonar

- docs/Tutorials.md
- src/main/java/com/checkmarx/flow/config/SonarQubeProperties.java
- src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
CxFlow will generate the report as for the format of sonarqube generic issue import format.
Below is the configuration for application.yml SonarQube:
```
cx-flow:
bug-tracker: SonarQube
bug-tracker-impl:
- SonarQube
```
```
sonarqube:
file-path: {FILE_PATH}
```
This will generate SonarQube Issue Report for CxFlow SCA Scan.
1. Set Sonar Scanner in Windows PATH Varaible. …
> [SCA Scan] Provide support for Generic Issue Format of Sonar

- build.gradle
> This PR fixes vulnerability in spring-core package reported by SCA.
Tested CxFlow in --web and --scan mode.
- [] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
> Fixed SCA vulnerability in spring-core package

- build-11.gradle
- build.gradle
> This PR fixes vulnerability in spring-core package reported by SCA.
Tested CxFlow in --web and --scan mode.
- [] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
> Pr fix sca vuln

- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/CliMode.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
> Documentation for PR - Issues in Jira should not be closed on re-run of other/alternate scan for same project. [#945](https://github.com/checkmarx-ltd/cx-flow/issues/945).
> [Include supporting link to GitHub Issue/PR number](https://github.com/checkmarx-ltd/cx-flow/pull/945)
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration …
> Documentation - Issues in Jira should not be closed on re-run of other/alternate scan for same project. #945

- build-11.gradle
- build.gradle
> This PR fixes the vulnerability present in tomcat-embed-core package.
>
> Please include any manual steps for testing end-to-end …
> Fixed tomcat vulnerability

- docs/Configuration.md
- docs/Execution.md
> Added documentation for scan queuing and scan queuing timeout and providing java_opts to a docker image.
> Added documentation For Scan Queuing and Docker

- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/Execution.md
> This PR adds documentation for the way CxSAST/CxSCA issues summary is reported on a PR and also the way to override application yml params through CLI.
> Added documentation For CLI params and Issue summary

- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
added scan-resubmit functionality for CLI mode.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests …
> added scan-resubmit functionality for CLI mode

- docs/Configuration.md
added missing parameters of cx-flow section …
> added missing parameters of cx-flow section

- docs/Bug-Trackers-and-Feedback-Channels.md
added correct xml scheme link
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete …
> added correct xml scheme link

- docs/Tutorials.md
> Documentation on CxFlow's Github wiki for integration with CircleCI.
>
> Please include any manual steps for testing end-to-end …
> [JIRA:CXFLW-30] CircleCI - Update ORB and CxFlow wiki documentation

- docs/Bug-Trackers-and-Feedback-Channels.md
>This PR fix image not showing in wiki for CxSAST summary
> Fix image not showing in wiki for CxSAST summary

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/BugTracker.java
used proper jql word in the code.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete …
> used proper jql word in the code.

- build-11.gradle
- build.gradle
Upgraded Spring boot,Spring Core and Tomcat version
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing …
> Upgraded Spring boot,Spring Core and Tomcat version

- docs/External-Scripts.md
> This PR fixes the links for the scan comment groovy script sample files.
> fixed documentation for Scan Comment groovy script

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
> This PR fixed the recommended version not appearing in CxSCA result summary.
> Created a PULL request in repositories present in GitHub and GitLab and Recommended version were showing the fixed version in both the SCMs.
> Fixed recommended version in sca result summary

- docs/CxSAST-Version-9.0.md
> This PR adds documentation of the least privileged cx-sast roles required by a user of cx-flow
> Added documentation for cx-sast roles required by a user of cxflow

- build-11.gradle
- build.gradle
- docs/Configuration.md
- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
- src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
For SAST Scan Result “Query->Result->Path” should match the “Sarif Issues->Show Path”. Flag will be used to enable/disable this functionality but will use starter workflow to set this flag default value in case of github actions.
e.g.:- starter-workflows/checkmarx.yml at main actions/starter-workflows .
Flag "--checkmarx.disable-clubbing=true" for GitHub Actions where SARIF is bug tracker, default value is false.
SCA results in the Security tab has not been mapped.
Correcting Source to Sink in the Path.
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/mas …
> [JIRA:CXFLW-47] CxFlow: Don't group findings for Sarif - GH Action Security Updates

- Dockerfile
added JAVA_HOME env variable in dockerfile …
> added JAVA_HOME env variable in dockerfile

- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
corrected typo error from pen to open …
> corrected typo error from pen-to open

- build-11.gradle
- build.gradle
- docs/Configuration.md
[JIRA:CXFLW-836] added  documentation for scope parameter.
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and …
> [JIRA:CXFLW-836] added scope documentation.

- .gitignore
- src/main/java/com/checkmarx/flow/service/FlowService.java
> Fix postback GitHub issue

- .gitignore
- Dockerfile
- build-11.gradle
- build.gradle
- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/service/EmailService.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/service/SendGridService.java
- src/main/resources/application.yml
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
This PR fixes below issues:
1. Dockerfile update to uptake new openjdk8 version
2. Fix test cases as test data used now shows less expected vulnerabilities.
3. Pulls changes from the PR#985
4. Undo change pulled from the PR#1014
None. These issues were seen from broken pipeline.
All tests on the pipeline have passed.
- [ NA] I have added documentation for new/changed functionality in this PR (if applicable).  *If …
> JDK8 new version uptake in the docker image and other pipeline fixes.

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
> Fixed NPE when Email was set as bug tracker in --scan and --project mode.
> #753 
> Manual Testing , Scanned project in CLI with --scan and --project mode with Email as a bug tracker and NPE occurred.
> [JIRA:CXFLW-17]Fixed Email as a bug tracker in scan and project mode

- build-11.gradle
- build.gradle
- docs/Config-As-Code.md
- src/main/java/com/checkmarx/flow/dto/FlowOverride.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/main/java/com/checkmarx/flow/service/IssueService.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> Merging Development changes in my branch

- build-11.gradle
- build.gradle
- docs/Config-As-Code.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/dto/FlowOverride.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/main/java/com/checkmarx/flow/service/IssueService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/service/ThresholdValidator.java
- src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> CXFLW-400 Adding changes for break build.

- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
> Fixed NPE when "enabled-zip-scan=true" in SCA scan.
> #938
> Manual Testing, Scanned project in gitLab pipeline, gitHub action and in CLI mode.
> CXFLW-378: SCA zip scan fails when run in pipeline

- .circleci/config.yml
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
- src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
- src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
> Pagintion code change along with tst case file change

- .circleci/config.yml
- src/main/java/com/checkmarx/flow/utils/MaskingPatternLayout.java
- src/main/resources/logback-spring.xml
We add a custom Logback Layout implementation that uses regular expressions to detect passwords and tokens in log messages and redacts them.
Addresses issue #1054 
Implementation based on https://www.baeldung.com/logback-mask-sensitive-data
> Describe how this …
> Redact passwords and tokens in log messages

- .circleci/config.yml
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/config/FlowAsyncConfig.java
- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/controller/TfsController.java
- src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
- src/test/resources/cucumber/data/cxflow-reference-reports/1-finding.json
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-different-files.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
- src/test/resources/cucumber/data/cxflow-reference-reports/3-findings-different-severity-medium-high-critical.json
- src/test/resources/cucumber/data/cxflow-reference-reports/empty-results.json
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
> CXFLW-58 Added Comments for debugging

- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
> Adding null check

- src/main/java/com/checkmarx/flow/service/JiraService.java
>Removed the GitLab CI token to the repository URL in Jira issues created.  
Manual Tested using GitLab and GitHub as bug trackers and tested using GitLab Pipeline.
> CXFLW-551 CxFlow adds the GitLab CI token to the repository URL in Jira issues created

- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
The project name is inconsistent while using GitHub Actions.
When a scan with `scanners: sast, sca` he gets projects called "retentionscience-predictinator-PR" in both SAST and SCA.
When a scan with only SCA (`scanners: sca`), then he gets a project called "retentionscience/predictinator-PR" in SCA.
> CXFLW-525 Fixed inconsistent project name for sca

- src/main/java/com/checkmarx/flow/service/JiraService.java
> Code change for test case fix

- .circleci/config.yml
- src/main/java/com/checkmarx/flow/service/JiraService.java
> Pr devpipeline fix

- Dockerfile
- build-11.gradle
- build.gradle
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
To provide the feature for on-prem utility that enables us to resolve and extract dependencies and fingerprints from source code using SCA Resolver tool and integrating with CxFlow.
> SCA Resolver Integration with Cx-Flow

- .circleci/config.yml
- src/main/java/com/checkmarx/flow/service/JiraService.java
> Go Lang Version Fix

- src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
> CXFLW-577 Fix for Git dashboard.

- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
The value obtained by team-script is not used to update the team property of ScanRequest object, so cx-flow will throw an exception on class/method CxService.validateScanParams. This PR fixes #1083
N/A
Configure the `application.yml` file as follows:
```yaml
server:
port: ${PORT:8080}
checkmarx:
team-script: team-script.groovy
azure:
webhook-token: cxflow:webhook
```
Configure the team-script.groovy as follows:
```groovy …
```
> Set the teamName obtained by the groovy script

- src/main/java/com/checkmarx/flow/controller/FlowController.java
Added Filter Severity in Postback Mode.
#1018 
Manual Testing in Postback mode.
> CXFLW-569 (GH 1018) ignoring filter-severity in postback mode

- build-11.gradle
- build.gradle
- docs/CxSCA-Integration.md
Fixed vulnerabilities issues 
CVE2022- 37434 ------ zlib------ 1.2.12-r1 ------ fixed in 1.2.12-r2
CVE2022- 34169, CVE2022- 21476, CVE2022- 21541, CVE2022- 21540, CVE2022- 21496, CVE2022- 21434, CVE2022- 21426 , CVE2022- 21443 openjdk8----- 8.322.06- r0 ------fixed in 8.345.01- r0
CVE2022- 29885 , CVE2022- 34305 -------- apache tomcat_tomcatembed-core 9.0.62-------- fixed in 9.0.65
> Vulnerability fix

- build-11.gradle
- build.gradle
> Pr verchange

- build-11.gradle
- build.gradle
Snake Yaml vulnerabilities fix excluded 1.30 and added 1.31 version.
> Snake-yaml vulnerability fix

- build-11.gradle
- build.gradle
> Updated SDK version

- build-11.gradle
- build.gradle
vulnerabilities-fix for tomcat-embed-core and ivy
> vulnerabilities-fix

- Dockerfile
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
> CXFLW-586 Pr groovyscript

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/test/resources/cucumber/features/componentTests/sca-thresholds.feature
> CXFLW-583 Pr breakthebuild cxflw 583

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/test/resources/cucumber/features/componentTests/sca-thresholds.feature
> Pr breakthebuild cxflw 583 Removing

- src/main/java/com/checkmarx/flow/service/JiraService.java
User wants to map the Similarity ID to a JIRA custom field
Something that needs to be considered is what if the ticket has multiple SIDs
Purpose
User wants the Similarity ID for reference.
Details
fields:
type: result
name: SimilarityId
jira-field-name: customfield_10036
jira-field-type: text
>  similarity id mapping to Jira

- src/main/java/com/checkmarx/flow/jira9X/FieldSchema.java
- src/main/java/com/checkmarx/flow/jira9X/IssueFields.java
- src/main/java/com/checkmarx/flow/jira9X/IssueType.java
- src/main/java/com/checkmarx/flow/jira9X/Project.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
When a custom field is configured to have a default value, an exception is thrown.
(https://github.com/checkmarx-ltd/cx-flow/issues/1165)
Tested on JIRA Cloud, 9.0 and8.20.10
> Jira default value fix

- Dockerfile
- build-11.gradle
- build.gradle
clean up for all the result files, clone directory and logs of sca resolver. 
Note : if LogsDirectory is set in Configuration.ini logs of sca resolver will not be removed.
https://github.com/checkmarx-ltd/cx-flow/issues/1129
> Changes for SCA Resolver files and log deletion

- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/Configuration.md
- docs/CxIAST-Integration.md
- docs/CxSAST-Version-9.0.md
- docs/CxSCA-Integration.md
- docs/Delete-Branch.md
- docs/Thresholds-and-policies.md
- docs/Tutorials.md
- src/main/java/com/checkmarx/flow/service/ASTScanner.java
- src/main/java/com/checkmarx/flow/service/CxGoScanner.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/SastScanner.java
Fixed SAST and SCA Order issue
https://github.com/checkmarx-ltd/cx-flow/issues/1131
> Fixed SAST and SCA Order issue

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
> CXFLW-582 Fix For Git pull request scan breakbuild fix

- build-11.gradle
- build.gradle
When ScaResolver is enabled changed origin in sca portal as ScaResolver-CxFlow
> ScaResolver Origin Change

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
> Break Build SAST and SCA Threshold issue fix

- build-11.gradle
- build.gradle
Tomcat version updated to 9.0.69
> SCA Vulnerability Fix

- src/main/java/com/checkmarx/flow/config/FlowProperties.java
> CXFLW-724 Fix for SAST Default value in arraylist

- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
Config as Code for scanResubmit parameter fix.
> ScanResubmit Config as Code fix

- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Link-To-SCA fix for bug-tracker JIRA , GitHub, GitLab
> link-to-SCA-fix

- Dockerfile
Changed Configuration.ini to Configuration.yml
> Changed Configuration.ini to Configuration.yml

- src/main/java/com/checkmarx/flow/custom/SonarQubeIssueTracker.java
When using SonarQube as bug-tracker, the resulting JSON report (to be imported into Sonarqube) does not include the attack vector into the secondaryLocations. This means that attack vector is not shown into Sonarqube.
As far as I see in the code, secondayLocations are not included.
sonarIssues.add(Issue.builder().engineId(properties.getSastScannerName())
.ruleId(issue.getVulnerability())
.severity(properties.getSeverityMap().get(issue.getSeverity()) != null ? properties.getSeverityMap().get(issue.getSeverity()):DEFAULT_LEVEL)
.type("VULNERABILITY")
.primaryLocation(ILocation.builder()
.filePath(issue.getFilename())
.message(StringUtils.isEmpty(issue.getDescription()) ? issue.getVulnerability() : issue.getDescription())
.textRange(TextRange.builder()
.startLine(k<1?1:k) …
> SonarQube Secondary path issue fix

- Dockerfile
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/JiraService.java
Fix For Jira On-prim null pointer exception for version less than 8.4
> Jira On-prim Fix for Lower version

- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
Fix bug related to #1184 
#1184 
This is currently running in our non-prod environment.
> fix create team for /scan

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
link to the file escaped and properly replaced spaces with %20
(https://github.com/checkmarx-ltd/cx-flow/issues/983)
> escaping spaces in pr decoration

- docs/Thresholds-and-policies.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
> CXFLW-719 Break build false

- docs/CxSCA-Integration.md
Fix for SCAResolver documentation
https://github.com/checkmarx-ltd/cx-flow/issues/1185
> ScaResolver documentation fix

- Dockerfile
- docs/External-Scripts.md
> Scan Comment Documentation fix

- docs/Configuration.md
- docs/CxSCA-Integration.md
- docs/External-Scripts.md
Added documentation for CLI and Environment variables
> Documentation fix 

- Dockerfile
- build-11.gradle
- build.gradle
updated versions for  jettison, snakeyaml, tomcat and springboot
> Vulnerabilities fix for 1.6.40 release

- build-11.gradle
- build.gradle
- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/Proxy-and-HTTPS-Configuration.md
- docs/Tutorials.md
Documentation update for Jira credentials and HTTPS config
> Documentation update for Jira 

- docs/Configuration.md
- docs/Thresholds-and-policies.md
> Pr cxflw 668 folder exclusion

- docs/Thresholds-and-policies.md
> CXFLW-659 Merge Id recognized.

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Jira On prim assignee endpoint fix
> On prim Assignee fix

- Dockerfile
- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
Adding error log for parse mode
(https://github.com/checkmarx-ltd/cx-flow/issues/746)
Tested on Parse mode for Both SAST and SCA
> Adding error log for parse mode

- docs/Configuration.md
Documentation Update for using Logstash with CxFlow log
https://github.com/checkmarx-ltd/cx-flow/issues/1121
> Documentation Update for using Logstash with CxFlow log

- build-11.gradle
- build.gradle
- docs/Bug-Trackers-and-Feedback-Channels.md
* Updated Jira documentation for increasing socket timeout error for jira 
* Updated sdk version for https://github.com/checkmarx-ltd/cx-flow/issues/1048
(https://github.com/checkmarx-ltd/cx-flow/issues/1048)
> Updated jira docs and sdk version

- Dockerfile
Alpine version update to 3.17.3
> Alpine version update

- Dockerfile
- build-11.gradle
- build.gradle
In this PR we are updating Alpine version and Checkmarx springboot SDK.
> Pr alpineandsdkversoionupdate

- docs/Tutorials.md
Documentation fix for tutorial chapter
> Tutorial docs fix

- build-11.gradle
- build.gradle
Fixed Vulnerabilities for tomcat and guava 
updated SpringBoot minor version from 2.7.11 to 2.7.13
> Vulnerabilities fix  for version 1.6.41

- src/main/java/com/checkmarx/flow/config/JiraProperties.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
Cx-Flow Jira tickets are closing incorrectly even though Vulnerability are not resolved.
This issues occurs while using scanner as SCA.
Tested on Jira on-prim and cloud.
> Jira closing issue for SCA

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
> ADO Pull request fix and sdk version update

- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
> Pr Version Update

- docs/Bug-Trackers-and-Feedback-Channels.md
Added new note for Jira transition
> Jira transition docs fix

- build-11.gradle
- build.gradle
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/service/ASTScanner.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/SCAScanner.java
- src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
Separate project name for SCA 
added new sca application.yaml parameter and config as code parameter named  `project-name `
> Separate SCA project name

- build-11.gradle
- build.gradle
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/SbomProperties.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
- src/main/java/com/checkmarx/flow/service/SbomService.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/GetResultsAnalyticsTestSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/ast/parse/GitHubCommentsASTSteps.java
- src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
Implemented new feature to generate sbom file.
> SBOM File implementation

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
If Recommended version does not exist should provide No Recommendations in table
https://github.com/checkmarx-ltd/cx-flow/issues/805
> SCA recommended version column fix

- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/RallyIssueTracker.java
- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/BitBucketService.java
- src/main/java/com/checkmarx/flow/service/CodeBashingService.java
- src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
Description
Scan Local Path Logging if error at SAST End. System should log exact message from SAST
Note: Confirm if the “git clone failure” contains more information. (Related to Anthenahealth: CxFlow logs in general are not clear on what causes “git clone failure” i.e. special char, long path, etc)
Steps to Reproduce
In Incremental SCAN try to add files having changes in more than 7% of files it will throw Scan Local path issue.
Actual Result
System logging Scan Local path issue.
Expected Result
It should log proper message
Possible solution
Code change required.
> CXFLW-742 Added additional logging.

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
Added new Label for JIRA (DEV or PROD)
> Jira new labels DEV or PROD

- docs/Troubleshooting.md
Description
User wants Cx-flow should log details in JSON Format
We need to document how users can get logs in JSON Format.
> CXFLW-833 Added document for generation JSON Logs from cx-flow

- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Fixed Recommended version column in GitLab merge request 
added condition for null as well as empty string
> GitLab Merge request Recommended version column fix

- build-11.gradle
- build.gradle
Vulnerability fix for ivy and tomcat 
updated ivy to 2.5.1 to 2.5.2
updated tomcat to 9.0.78 to 9.0.80
> Vulnerability Fix for ivy and tomcat

- src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerScanEventHandler.java
Fixed bitbucket server token parameter for special characters
Tested on bitbucket server 8.9.0
Tested on bitbucket cloud
> Fixed Bitbucket server token issue

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
> null Pointer fix

- README.md
- docs/Home.md
- docs/Prerequisites-and-Requirements.md
Added notice related to Java Older version
> Added Notice for Java Versions

- Dockerfile
- build-11.gradle
- build.gradle
- src/main/resources/application.yml
- src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/policy_management/ScaPolicyManagementSteps.java
Fixed Libcurl vulnerability and updated alpine version
> Fixed libcurl vulnerability

- docs/Bug-Trackers-and-Feedback-Channels.md
> CXFLW-970 Gitlab project issue

- Dockerfile
- build-11.gradle
- build.gradle
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
Added excludeFiles, fingerprintsIncludePattern, ManifestsIncludePattern for config as code
> Added SCA include pattern in Config as code

- Dockerfile
- src/main/java/com/checkmarx/flow/config/RepoProperties.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
Fixed cx-summary property 
https://github.com/checkmarx-ltd/cx-flow/issues/1115
> Fixed cx-summary property

- Dockerfile
- build-11.gradle
- build.gradle
- docs/Config-As-Code.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
- src/test/java/com/checkmarx/flow/cucumber/component/commentscript/CommentScriptSteps.java
Added new checkmarx parameter for both yaml and config as code. default value for both is true.
Yaml
```
checkmarx:
public-scan: false
```
Config as code
```
{
"version": 1.0,
"project": "XYZ-${repo}-${branch}",
"team": "/a/b/c",
"sast": {
"publicScan" : "false"
}
}
```
> Sast private scan changes

- build-11.gradle
- build.gradle
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
Fixed vulnerabilities for Json and tomcat
> Security vulnerabilities fix

- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
> CXFLW-1003 Gitlab draft issue fix

- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
Fixed startColumn  -1 for Sarif report
> Fix for startColumn  -1 in sarif format

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/GitLabService.java
> Code changes for exceptions

- build-11.gradle
- build.gradle
- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/controller/ADOController.java
- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/controller/GitLabController.java
- src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java
- src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/JsonProperties.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/handlers/bitbucket/server/BitbucketServerPushHandler.java
Added latest committer email for JSON bug tracker
created a new Boolean JSON property  latest-committer-email
> Added latest committer email for JSON bug tracker

- Dockerfile
- build-11.gradle
- build.gradle
Vulnerability fix for log-back ,tomcat and upgraded spring-boot version to 2.7.18
> Vulnerability fix for 1.6.46 release

- build-11.gradle
- build.gradle
- docs/Thresholds-and-policies.md
> Version Update

- build-11.gradle
- build.gradle
- docs/Thresholds-and-policies.md
> Pr cxflow documentation

- .circleci/config.yml
> Hi This is me

- .circleci/config.yml
> Pr springbootmigrationprodtesting

- README.md
- docs/Configuration.md
- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
- src/main/java/com/checkmarx/flow/utils/ZipUtils.java
- src/test/java/com/checkmarx/flow/cucumber/integration/ziputils/zipUtilsSteps.java
Added new parameter zip-include for cx-flow.
```yaml
cx-flow:
zip-include: \.git/.*, .*\.png
```
(https://github.com/checkmarx-ltd/cx-flow/issues/1300)
Tested on CLI and GitHub Action.
> Added new parameter zip-include for cx-flow

- README.md
- src/main/java/com/checkmarx/flow/dto/github/Issue.java
Changed issue dto  filedname id's datatype from int to long  
Tested with bug-tracker GitHub
> Changed id datatype from int to long

- README.md
- docs/Bug-Trackers-and-Feedback-Channels.md
Updated documentation  for Jira Skip Update and added documentation for cx-sca tag
> Updated documentation for Jira Skip Update

- build-11.gradle
- build.gradle
Updated springboot tomact version
> Updated springboot tomact version

- .circleci/config.yml
- build.gradle
- docs/Configuration.md
- docs/Thresholds-and-policies.md
> Added documentation and circle cir configuration changes

- build-11.gradle
- build.gradle
Fixed vulnerability for logback-core and classic
> Fixed vulnerability for logback

- docs/Bug-Trackers-and-Feedback-Channels.md
- src/main/java/com/checkmarx/flow/config/JiraProperties.java
- src/main/java/com/checkmarx/flow/constants/JiraConstants.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
Fixed Jira description overflow issue by adding new parameter `max-description-length`
```yaml
jira:
max-description-length : 10
```
Tested on SCA and SAST
> Fixed Jira description overflow issue

- src/main/java/com/checkmarx/flow/service/HelperService.java
> CXFLW-1093 added code for pattern support in branch list

- build-11.gradle
- build.gradle
Vulnerability Fixed for spring-web, xmlunit-core, bcprov-jdk18on, software.amazon.awssdk
> Vulnerability fix for 1.7.01

- src/main/java/com/checkmarx/flow/config/SarifProperties.java
- src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
> CXFLW-1050 CXFLW-1086 CXFLW-1217 Fix

- .circleci/config.yml
- Dockerfile
- src/main/java/com/checkmarx/flow/CxFlowApplication.java
- src/test/java/com/checkmarx/flow/cucumber/component/projectkeyscript/JiraProjectKeyScriptSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/jira/analytics/JiraAnalyticsOpenIssueViaCommandLineSteps.java
In the rapidly evolving world of software development, adapting to new operating systems and maintaining robust, secure, and efficient pipelines are crucial. Recently, I undertook the challenge of enhancing our system's compatibility with a new operating system (OS) and simultaneously addressed several significant issues within our Continuous Integration/Continuous Deployment (CI/CD) pipeline. These issues included a JIRA ticket, Software Composition Analysis (SCA) concerns, and problems identified by Static Application Security Testing (SAST) Command Line Interface (CLI) tools. This documentation provides an in-depth look into the work carried out, the challenges faced, and the solutions implemented.
Adding Support for a New Operating System
Identifying the Need
The first step was …
> CXFLW-1345 pipeline integration task

- src/main/java/com/checkmarx/flow/service/IssueService.java
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
Removed codeBashing Training Links From BugTrackers
https://github.com/checkmarx-ltd/cx-flow/issues/1342
Tested on SCAN and WEB mode for Both SAST and SCA With BugTracker Jira
> Removed codeBashing Training Links

- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
Label issue for severity info fixed for bugTracker GitHub and GitLab.
https://github.com/checkmarx-ltd/cx-flow/issues/1340
Tested on GitLab and GitHub
> Fixed Label issue for Info

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/ADOProperties.java
Added ADO git clone feature --ado cli parameter 
(https://github.com/checkmarx-ltd/cx-flow/issues/733)
Tested with ADO bug-tracker and enabled-zip-scan parameter
> Added ADO git clone feature

- build.gradle
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
This is the CxFlow log, the customer would like to see at the end (after the "Completed Successfully" message) the vulnerabilities count
Requested by [@Sangeetha Ravikumar](https://checkmarx1.aha.io/users/7088198271844914738) in FR https://checkmarx1.aha.io/ideas/ideas/SDLC-I-96?active_tab=idea_comments
> CXFLW-1230 add vulnerability summary

- docs/Configuration.md
- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/dto/ScanRequest.java
- src/main/java/com/checkmarx/flow/dto/github/PullRequest.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/ResultsService.java
Describe the problem
For GitHub integrations (possibly others as well), it is only possible to configure automatic project deletion in CxFlow on branch/tag deletion events. For teams using a fork based git flow (only create PRs from forked repos), however, this means that PR projects will never be deleted, since branch deletion event is never sent for forks. Even if these teams try to work around that by installing the CxFlow webhook in their forked repos, branch deletion event will not be processed for the intended Checkmarx project unless the team and project name is overridden using config or groovy scripts, which even then is very difficult since the deletion event data does not include any references to the original PR.
Also (though less important) — some teams do not want to keep …
> CXFLW-1233 Added code for project deletion on PR close event.

- Dockerfile
- docs/Configuration.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/BitBucketProperties.java
- src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cli/iast/IastCliSteps.java
Added bitbucket cloud and server git clone
https://github.com/checkmarx-ltd/cx-flow/issues/732
Tested with bitbucket cloud and server version 8.2.1
> Added bitbucket cloud and server git clone

- templates/gitlab/v4/Checkmarx.gitlab-ci.yml
> Added branch support in Checkmarx within a GitLab pipeline template. This enhancement enables branch support from Cx-Flow by utilizing GitLab environment variables to automatically detect whether we are on the master branch or a feature branch. Consequently, it creates a corresponding branch project or a basic project accordingly.
> N/A
> I verified that when we are on the default branch, it correctly creates a "normal" project.
> I tested the branch creation.
> I tested branch names with special characters, which are correctly supported.
> Added support for branches in GitLab CI template

- src/main/java/com/checkmarx/flow/service/JiraService.java
CxFlow jira issues which are marked as Not exploitable in SAST is not getting closed
Tested in SAST 
Scan project with parameters
filter-severity:
-high
filter-state:
-to verify
-confirmed
After scan mark few vulnerabilities not exploitable in SAST and Scan again. Vulnerabilities marked as not exploitable should get closed
test case passed.
> Fixed Jira not closing issues marked Not Exploitable in SAST

- build.gradle
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
Added Similarity ID to new Line for issue trackers 
(https://github.com/checkmarx-ltd/cx-flow/issues/1343)
Tested on GitLab
> Added Similarity ID to new Line

- build.gradle
- src/test/resources/cucumber/data/cxflow-reference-reports/11-findings.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-severity.json
- src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-same-vuln-type-same-file.json
Vulnerability fix for tomcat 
updated tomcat from 10.1.19 to 10.1.25
> Vulnerability fix for 1.7.02

- README.md
- docs/Home.md
> Removed Notice

- build.gradle
- src/main/java/com/checkmarx/flow/utils/ZipUtils.java
Added changes so that symbolic link can also be zipped. 
https://github.com/checkmarx-ltd/cx-flow/issues/842
Tested on Linux Ubuntu
> Added Symbolic link zip feature

- src/main/java/com/checkmarx/flow/service/ADOService.java
- src/main/java/com/checkmarx/flow/service/BitBucketService.java
- src/main/java/com/checkmarx/flow/service/GitHubService.java
Changed StackTrace messages from error to debug. This will not show unnecessary stack trace for expected cases and we will be able to debug it if debug is enabled.
(https://github.com/checkmarx-ltd/cx-flow/issues/1194)
Tested on scm tools
> Changed StackTrace logs from error to debug

- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/config/BitBucketProperties.java
Added bitbucket pull feature through CLI 
(https://github.com/checkmarx-ltd/cx-flow/issues/1125)
> Added CLI bitbucket pull feature

- build.gradle
- src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
- src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
Updated version for springboot to 3.2.10
> Fixed Vulnerability for 1.7.04

- src/main/java/com/checkmarx/flow/controller/GitHubController.java
- src/main/java/com/checkmarx/flow/dto/github/PullRequest.java
Fixed Integer Overflow for GitHub Pull Request Class. Changed Id Type to Double.
Tested on GitHub Cloud.
> Changed Integer to Double for ID

- build.gradle
Updated spring-boot version from 3.2.10 to 3.2.11
Updated Spring-core version from 6.1.6 to 6.1.14
Updated commons-io version from 2.11.0 to 2.14.0
> Security Vulnerability fix for 1.7.05

- build.gradle
sca-resolver support added when preserve-project-name: true and project name contains space. 
Tested with sca-resolver
> Sca Resolver project name with space fix

- Dockerfile
- src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
ADO on-prem workItem issue fixed.
Tested with SAST 9.7 with ADO cloud and ADO server 2019
> Fixed ADO on-prem workItem issue

- src/main/java/com/checkmarx/flow/service/GitHubService.java
- src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
Added validate branch before config as code. By doing so validating if branch exists or not before downloading config as code.
> Added validate branch before config as code

- src/main/java/com/checkmarx/flow/config/FlowProperties.java
- src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
- src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
> CXFLW-1506 Added code for comment off concurrent PR scans

- build.gradle
Updated version
software.amazon.awssdk:dynamodb
software.amazon.awssdk:regions
software.amazon.awssdk:auth
software.amazon.awssdk:sts 
tomcat
> security fix for verison 1.7.06

- docs/CxSCA-Integration.md
Added documentation for ways to add dependency resolution utilities in cx-flow docker image.
> Added documentation for ScaResolver

- build.gradle
- docs/External-Scripts.md
- src/main/java/com/checkmarx/flow/CxFlowRunner.java
- src/main/java/com/checkmarx/flow/service/ExternalScriptService.java
- src/main/java/com/checkmarx/flow/service/FlowService.java
- src/main/java/com/checkmarx/flow/service/HelperService.java
Description:
The Groovy script is designed to change any backslashes (\) in the project name to underscores (_), and this works fine. However, when merging a feature branch (e.g., abc) into a development branch (e.g., release/integration), the forward slash (/) in the branch name is not replaced by an underscore (_). This leads to issues with the project branching logic, which expects underscores in place of slashes.
Steps to Reproduce:
Create a development branch with the name release/integration.
Create a feature branch with the name abc.
Attempt to merge the feature branch into the development branch.
Observe that the forward slash in the development branch name (release/integration) is not replaced by an underscore (release_integration).
Expected Behavior:
The script should replace …
> CXFLW-1604 Pr cxflw 1604 groovy script issue

- docs/Tutorials.md
updated bitbucketpull documentation
> updated bitbucketpull documentation

- src/main/java/com/checkmarx/flow/dto/github/CxFlowCommandHandler.java
> Added code for execution for test case

- build.gradle
Updated version for logback, tomcat and netty.
> Vulnerability Fix for 1.7.07

- build.gradle
- docs/Config-As-Code.md
- src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
> Pr cxflw 1607 cxconfig comment off

- build.gradle
> CXFLW-1642 version update

- docs/Bug-Trackers-and-Feedback-Channels.md
- docs/CxSCA-Integration.md
- src/main/java/com/checkmarx/flow/service/JiraService.java
- src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
- src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature
Added new custom field for JIRA specific for sca-results
```yaml
jira :
fields :
- type: sca-results
name: cvss-score
jira-field-name: cvss-score
jira-field-type: label
```
Tested with SCA with JIRA as a bug-tracker.
Tested Basic features of cx-flow with JIRA integrations
> Added new Custom field for JIRA

- src/main/java/com/checkmarx/flow/dto/azure/Resource.java
- src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
> Few fixes related to jsonIgnore and comments- ADO-PR-Decoration-comments

- Dockerfile
- build.gradle
- src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
Null check and warning messages for GitLab Dashboard
> Null check for GitLab Dashboard

- Dockerfile
Undoing changes as cx-flow GitHub action will fail.
> Undo Dockerfile Changes

- build.gradle
Vulnerabilities fix for spring boot, spring, tomcat, jgit
Tested with SAST 9.7 and SCA
> Vulnerability fix for version 1.7.10
