build-11.gradle
build.gradle

Fix issue with Checkmarx SDK (Version 0.4.8) where the false positive calculation was inaccurate.

Fix SDK False Positive count

---

.circleci/config.yml

Remove Docker Registry reference.  This will require the Environment variable DOCKER_REPO to be set in the circleci settings.
ie., DOCKER_REPO=docker.io/checkmarxts/cxflow

Remove hard coded Docker Registry

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java

Without this explicit exit, certain situations will cause a hanging process at the.  This fix was required for a client in their production environment with the latest build.

Fix hanging process when using CLI

---

build-11.gradle
build.gradle

Resolving team path inconsistencies by initializing the team path with a leading path separator (\ or / depending on 8.X vs 9.X)

Update SDK to 0.4.9 to fix Team path inconsistencies

---

src/main/java/com/checkmarx/flow/utils/ScanUtils.java

Azure Item 74 - Threshold functionality doesn't work if flow-summary is true
Update logic to get instead of put, which is not accurate.

Fix Threshold when using Flow Summary

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/config/FlowConfig.java

Fix For Azure Board Item 85
- Allow for Http Proxy settings provided to JVM
- Update Checkmarx SB SDK to 0.4.12
- Adding TO_VERIFY as status filter option
- Fix NPE when team is empty

Add Support for JVM Http Proxy Settings

---

src/main/java/com/checkmarx/flow/service/GitHubService.java

Rolled back the functionality that updates GitHub comments, because it currently causes errors.

Rolled back the functionality that updates GitHub comments

---

src/main/java/com/checkmarx/flow/controller/ADOController.java
src/main/java/com/checkmarx/flow/controller/TfsController.java
src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java
src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java

An error occurred during ADO-to-ADO 'push' flow. Namespace appeared twice in API URLs, e.g.
`https://dev.azure.com/MyNamespace/MyNamespace/MyProject/...`
was used instead of
`https://dev.azure.com/MyNamespace/MyProject/...`
As a result, ADO API calls failed.
Fixed by using ADO API base URL from CxFlow config, instead of using account.baseUrl from a webhook request.

Fixed errors in ADO-to-ADO flow

---

src/main/java/com/checkmarx/flow/bug_tracker_trigger/BugTrackerTriggerEvent.java
src/main/java/com/checkmarx/flow/dto/RepoComment.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
src/test/java/com/checkmarx/flow/cucumber/component/pullrequestanalytics/AnalyticsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/ThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsTestRunner.java
src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature

> CxFlow used to add comments to PR every time a scan was initiated for the PR. This caused a lot of verbosity in the PR page. Now CxFlow updates existing comments to reduce verbosity.
> https://github.com/checkmarx-ltd/cx-flow/issues/185
> There are two automation (integration) tests. First tests a PR without any comments and validates that there are two CxFlow comments. Second test tests for a PR that already have …

Pr udi update repo comment seperate comments

---

src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java

GitLabIssueTrack would sometimes find the wrong project when searching for exciting project information. The API call returns a list of all Projects that match the string being searched for but the code assumed that an exact match would occur and only one project would ever be returned. This resulted in situations where issues were sometimes being cut to the wrong project. For example when searching for: dvna-0429-1 the API would return dvna-0429-1 but also projects with names dvna-0429-11 and dvna-0429-10. If dvna-0429-1 was the first project in the list then the wrong project would be selected.
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please …

Fix for issue where GitLabIssueTrack would sometimes find the wrong project when searching for exciting project information

---

src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java

The issue occurred if there were several projects with similar name but in different namespaces.
In this case CxFlow took the first match from the list, without taking namespace into account. The first match isn't necessarily the project ID that we are looking for.
Fixed by matching against both project and namespace.
Namespace and project should be taken exactly as they appear in repo URL (this is called "project path" and "namespace path" in GitLab.
E.g. if repo URL displayed in browser is https://gitlab.com/my-namespace/my-awesome-project,
then `my-namespace` and `my-awesome-project` must be specified in CxFlow. Project and namespace names may be different from paths. E.g. project name may look like "My Awesome Project" and **should not** be used in CxFlow.
[Work …

Fixed: GitLab - getting project ID by name sometimes returns incorrect result

---

src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java

There was a bug in the way cx-flow loaded issues from GitHub and GitLab, it used pagination's of 100 issues per page, but read the issues only from the first page.
performing a scan with more than 100 xissues repeatedly, created new issues in each run. 
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/140/
tested on a GitHub repo with 286 issues and a scan with 113 xissues + debug to confirm all issues and xissues correspond to expected.
manual steps for testing end-to-end or functionality not covered by unit/integration tests:
* create a repo with over 100 issues (I used a subset of OWASP benchmark)
* run scan multiple times
* verify that no new bugs are opened after first run.
- this is a bug, no change in documentation is needed
- test reproduced on master (1.6.1) and develop, and …

fix bug #140 duplicated issues

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/config/FlowConfig.java
src/main/java/com/checkmarx/flow/controller/ADOController.java
src/main/java/com/checkmarx/flow/controller/AdoControllerBase.java
src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
src/main/java/com/checkmarx/flow/controller/FlowController.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/controller/GitLabController.java
src/main/java/com/checkmarx/flow/controller/TfsController.java
src/main/java/com/checkmarx/flow/controller/WebhookController.java
src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
src/main/java/com/checkmarx/flow/dto/azure/AdoDetailsRequest.java
src/main/java/com/checkmarx/flow/filter/CaseTransformingFilter.java
src/main/java/com/checkmarx/flow/filter/ParameterOverridingWrapper.java
src/main/java/com/checkmarx/flow/service/FilterFactory.java
src/main/java/com/checkmarx/flow/utils/ScanUtils.java
src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
src/test/java/com/checkmarx/flow/cucumber/component/filterscript/FilterScriptSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
src/test/java/com/checkmarx/flow/utils/github/GitHubTestUtils.java

Returning technical debt: webhook handler methods had lots of arguments. These arguments are bound to request query string. This made the controller code difficult to maintain and read. 
The main changes:
- extract arguments that are common for the controllers into a separate class (ControllerRequest)
- extract the common arguments of ADO/TFS controllers into the AdoDetailsRequest class
- extract duplicate code into base classes: WebhookController and AdoControllerBase
Some query string parameters are defined using kebab case, e.g. `exclude-files`. Spring Boot doesn't support binding such parameters to class fields out of the box. To fix this, CaseTransformingFilter was added.
[Work item 154](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/154/).
The changes are covered by existing …

Encapsulate webhook controller arguments into a single class

---

src/main/java/com/checkmarx/flow/service/SastScanner.java

> When running Cx-Flow in CLI mode with project name which contains a '/', the following error will occur:
`HTTP error code 400 BAD_REQUEST while creating project with name dctrn_javaapp_test/k8sCheckmarx under owner id b2252452-0a5f-42a0-8a37-ab803e1a40ac`
Fixed #314 
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/190

Fixed: Normalize project name in CLI mode to prevent bad characters on project name

---

src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/scaPR/ScaThresholdsSteps.java
src/test/resources/cucumber/features/componentTests/thresholds.feature

thresholds.feature tests failed with NullPointerException if sca-thresholds.feature tests were executed first.
Caused by the same instance of CxProperties that is shared across component tests. 
The issue only reproduced sometimes, because test execution order is not fixed and may change from build to build.
The SCA test overrides enabled vulnerability scanners list in FlowProperties with [sca]. When the SAST test was executed after the SCA tests, it used the scanner list from FlowProperties as is (which is incorrect).
Fixed by explicitly setting enabledVulnerabilityScanners to [sast] at the beginning of the SAST test.

Fixed: SAST threshold tests sometimes failed after SCA threshold tests were added

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java
src/main/java/com/checkmarx/flow/service/SastScanner.java

… for both/all scanners will need future consideration
CLI Execution was processing results twice.  This change will resolve this.
Logic was removed related to Future processing as the scans were not properly Async compatible.   This should be handle in the future.
Manual testing against GitLab and GitHub were conducted to validate the fix.

Fix CLI Execution from processing results twice

---

src/main/java/com/checkmarx/flow/controller/GitHubController.java

Set the default branch in GitHubController's PR handler (like it is set in the push handler), so that PRs are processed against the default branch when no branches are listed in the Flow properties.

set default branch in GitGubController PR handler

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/dto/report/PullRequestReport.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigTestRunner.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/config_as_code/ScaConfigAsCodeSteps.java
src/test/resources/cucumber/data/input-files-toscan/cx.config.src

> config as code parameters overrides scan-request object instead of properties files which have caused a bug in the main flow.
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/201
Proper test are validates configuration properties are withing the scanRequest.

Fixed: config as code parameters overrides scan-request object instead of properties files

---

src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/config/RepoProperties.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/HelperService.java
src/main/java/com/checkmarx/flow/service/RepoService.java
src/main/java/com/checkmarx/flow/service/SastScanner.java
src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchRunner.java
src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/resources/cucumber/features/componentTests/delete-branch.feature
src/test/resources/cucumber/features/integrationTests/cxconfig.feature

This is what happened before the fix:
Suppose user has a 'MyRepo' repository with 'featureBranch' that contains config-as-code. The config-as-code contains
```
"project": "foo-${branch}"
```
no Groovy script for project name generation is present, and 'multi-tenant' is set to 'true' in application.yml.
1. User scans featureBranch with CxFlow => CxFlow creates a SAST project with the name: **foo-featureBranch** (see ConfigurationOverrider#overrideMainProperties).
1.   User deletes 'featureBranch' => 'Branch deleted' event arrives to CxFlow.
1. CxFlow determines corresponding SAST project name as **MyRepo-featureBranch** (see ProjectNameGenerator.determineProjectName()). This happens because CxFlow no longer has access to config-as-code (it was deleted together with the branch).
1. CxFlow …

Fixed: CxFlow tries do delete a wrong SAST project when the project name was defined in config-as-code

---

build.gradle
src/main/java/com/checkmarx/flow/config/OptionalScmInstanceProperties.java
src/main/java/com/checkmarx/flow/config/RepoProperties.java
src/main/java/com/checkmarx/flow/config/ScmConfigOverrider.java
src/main/java/com/checkmarx/flow/config/ScmConfigParams.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
src/main/java/com/checkmarx/flow/dto/ControllerRequest.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/test/java/com/checkmarx/flow/controller/GitHubControllerTest.java
src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/githubflow/PublishingSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/ConfigAsCodeBranchSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/PublishTicketsWithOptionalScmConfSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/multiScmInstances/RunPublishTicketsWithOptionalScmConfSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sast/config/OverwritingProjectConfigSteps.java
src/test/resources/cucumber/features/integrationTests/jira/publish-processing.feature

> Enable multiple optional SCM's instances on Cx-Flow configuration
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/231
Integration test with optional instance was created, while default configuration is on comment-out
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

Added support for multiple optional SCM's instances

---

src/main/java/com/checkmarx/flow/controller/GitHubController.java

This PR is a clone of the PR #364 
Description
Previously, the GitHubController would set the clone URL to the repository's clone URL (equivalent to the PR base branch clone URL); this commit instead sets the clone URL to the clone URL of the pull request HEAD, so that scanned code changes are pulled from the correct repository, whether the PR was from a branch in the same repo or from a branch in a forked repository.
References
#363
Testing
To demonstrate failure case:
Fork a repo that is configured with CxFlow webhook
Create a branch name that does not exist on the source repository
Make a commit on that forked branch
open a PR from the forked repo, asking to merge your forked branch onto the default branch of the source repo
observe that CxFlow fails to process the event since it …

fix #363 - github PR from forked repo handling #364 (clone of other PR with same nme)

---

src/main/java/com/checkmarx/flow/controller/GitHubController.java

this is a clone  of PR #368 
> This fixes a breaking issue for our environment. We have the autoProfile property set to false in our environment, because when autoProfile is enabled, CxFlow hits an exception during commit & PR events when it calls the profile-related GitHub APIs (perhaps because the GitHub Enterprise service account we use does not have the needed scopes/permissions for those APIs) and so that exception causes processing of those event to fail and CxFlow doesn't create the project and/or kick off Checkmarx scans. I think it's apparent that the line this PR deletes was a typo anyway, because it globally overrides the autoProfile property on branch deletion events, so we would see things working as normal (autoProfile disabled) until a branch deletion event was processed, …

Fixed: Remove hard coded auto profile setting to TRUE on GitHubController flow

---

src/main/java/com/checkmarx/flow/dto/github/LabelsItem.java

In preparing for a POC, we encountered an issue with Github repository enabled with Dependabot security (Github SCA solution); this is used by the prospect for SCA
During the parsing of existing Github issues, error was flagged while extracting the response - JsonMappingException: Numeric value (2175583853) out of range of int (-2147483648 - 2147483647)
Cases 00056883
N/A

change labels id to long in github

---

README.md
build-11.gradle
build-cxgo.gradle
build.gradle
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/controller/FlowController.java
src/main/java/com/checkmarx/flow/dto/ExitCode.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/OsaScannerService.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java
src/main/java/com/checkmarx/flow/service/SastScanner.java
src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java
src/main/java/com/checkmarx/flow/utils/ZipUtils.java
src/test/java/com/checkmarx/flow/controller/FlowControllerTest.java
src/test/java/com/checkmarx/flow/cucumber/component/analytics/get/GetResultsAnalyticsTestSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/analytics/pullrequest/AnalyticsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/ast/parse/GitHubCommentsASTSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature

Provided that `enabled-vulnerability-scanners` property in application.yml contains `sca`, CxFlow command line will look like the following:
`java -jar cx-flow-1.6.5.jar --project --cx-project=my-sca-project --app=my-app`
There are several edge cases:
-    specified SCA project doesn't exist
-   SCA project has no scans
-   all scans for the SCA project failed
In these cases no issues will be published. However, no errors will be thrown either (only log messages appear).
Work item [219](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/219).
New scenarios were added to scaCliScan.feature.

Implemented getting and publishing latest SCA scan results in CLI mode

---

src/test/java/com/checkmarx/flow/cucumber/integration/ast/AstCommonSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerConfiguration.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestConfiguration.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/filters/ScaFiltersSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/scans/SCARemoteRepoScanSteps.java
src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature

purpose of this pull request is to improve the time of pull-request-comments integration tests
now we use cxService mocker to mock sast scans instead of perform more many scans on the same project with the same results - which doesn't effect the pr-comments functionality
there are no changes in production code

improve pr-comment tests

---

src/main/java/com/checkmarx/flow/config/FlowConfig.java
src/main/java/com/checkmarx/flow/config/FlowProperties.java
src/main/java/com/checkmarx/flow/service/EmailService.java

> This PR fixes an issue with email template, where an exception was being thrown in case the template name was blank. Added a mechanism to use a cxflow's default template.
> #405 
> Manual Testing done using GitHub webhooks.

Fixes Issue #405 : Exception thrown in case of blank email template name.

---

build-cxgo.gradle

- Update CxGo SDK to 0.1.34, which includes using V1 of published CxGo APIs
- Allow for external script to be called before zipping cloned source to be sent for scanning
N/A
This is an SDK upgrade for CxGo implementation.  Integration tests are performed against the pipeline for the SDK.  All existing CxFlow integration tests are applicable for this update.

Update CxGo SDK to 0.1.34

---

src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java

determine of project name using groovy script fails silently, if return type was not java.lang.String.
now it will throw an IO exception (will be loved, that return type must be a java.lang.String
#378 
N/A

enforcing groovy return trype

---

src/main/java/com/checkmarx/flow/config/ADOProperties.java
src/main/java/com/checkmarx/flow/controller/ADOController.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/service/ADOService.java
src/main/java/com/checkmarx/flow/service/FlowService.java
src/main/java/com/checkmarx/flow/service/SastScanner.java
src/test/java/com/checkmarx/flow/cucumber/component/deletebranch/DeleteBranchSteps.java
src/test/resources/cucumber/features/componentTests/delete-branch.feature

purpose of the pull request is to implement Delete Cx-project on Azure devops branch deletion
STORY 127 - Azure devops: when PR is closed, automatically delete a corresponding SAST project
Added component tests for delete branch feature for ADO implementation

delete Cx-project on ado delete branch event

---

src/test/java/com/checkmarx/flow/cucumber/component/parse/RunningCxFlowSteps.java

Fix parse component tests: 
force bug-tracker: Json to the Parse flow

fix parse component tests

---

src/main/java/com/checkmarx/flow/utils/ScanUtils.java

> This fixes the issue for the link containing the line number mentioned in PR comment for Bitbucket Cloud. Now the latest commit hash is used to refer to the branch instead of the branch name. This will avoid the broken links due to branch names that contain '/'.
> #159 
> Manual Testing done.

BBCloud : Fix for broken source link due to forward slash(/) present in branch name.

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature

Fixed incorrect search behavior for GitLab projects whose namespace path contains multiple segments.
[GitHub issue](https://github.com/checkmarx-ltd/cx-flow/issues/430)
[Work item](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/285)
Tested manually.

Fixed incorrect search behavior for GitLab projects

---

build-11.gradle
build-cxgo.gradle
build.gradle
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/aop/LoggingAop.java
src/main/java/com/checkmarx/flow/config/external/ASTConfig.java
src/main/java/com/checkmarx/flow/constants/FlowConstants.java
src/main/java/com/checkmarx/flow/controller/ADOController.java
src/main/java/com/checkmarx/flow/controller/BitbucketCloudController.java
src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java
src/main/java/com/checkmarx/flow/controller/FlowController.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/controller/GitLabController.java
src/main/java/com/checkmarx/flow/controller/TfsController.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/JiraService.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/test/java/com/checkmarx/flow/cucumber/integration/azure/publishing/github2ado/Github2AdoSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/config_provider/remote_repo/ConfigProviderRemoteRepoTestRunner.java
src/test/resources/cucumber/features/integrationTests/configProvider/remoteRepo/configProviderRemoteRepo.feature

> Support reading bean configuration from remote repo via Config-Provider component. This PR is relevant for AST & SCA scanners via GitHub remote repo.
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/249
>https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/222
1. Integration & component test were added on both Cx-flow and Config-Provider component.

Support reading bean configuration from remote repo via Config-Provider component

---

.circleci/config.yml
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/main/java/com/checkmarx/flow/service/ThresholdValidator.java
src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/sastPR/ThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/thresholds/scaPR/ScaThresholdsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sca/ScaCliSteps.java
src/test/java/com/checkmarx/test/flow/config/CxFlowMocksConfig.java
src/test/resources/cucumber/features/componentTests/sca-thresholds.feature
src/test/resources/cucumber/features/componentTests/thresholds.feature
src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature

Purpose of this PR is to add threshold logic for cxflow cli flows
Now user can configure thresholds to control break-build operations
Documentation guide: https://github.com/checkmarx-ltd/cx-flow/wiki/Thresholds-and-policies
Add automation voerage to cover cli flows in the following feature files:
- thresholds.feature
- sca-thresholds.feature

Pr add break build thresholds

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/main/java/com/checkmarx/flow/service/SastScanner.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/sast/SastCliSteps.java
src/test/resources/cucumber/features/integrationTests/cli/sastCliScan.feature

Fix bug tracker None for SAST scanner
when bugTrracker is None CxFlow should not wait for scan results, and finish the execution with success return code
this PR come to fix the issue for SAST. additional bug added to the backlog to support bug Tracker None to SCA\AST (BUG 298)
Bug Tracker of NONE not functioning as expected #445
Added automation in 
integrationTests/cli/sastCliScan.feature

fix bug tracker None not functioning as expected

---

src/main/java/com/checkmarx/flow/service/ASTScanner.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java

when running AST or SCA scans while the bug tracker is NONE, we don't want the scan to block the PR.
the change is that now, if the bug tracker is NONE, we will run the scan and update the results in a background thread.
BUG 298 - BugTracker None is not supported for AST\SCA scanners
verified manually that PR is not blocked
verified manually that the report is updated after the scan finishes

Pr ofer@ast no wait on none

---

build-11.gradle
build-cxgo.gradle
build.gradle
src/main/java/com/checkmarx/flow/controller/FlowController.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/FilterFactory.java
src/main/java/com/checkmarx/flow/service/OsaScannerService.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/main/java/com/checkmarx/flow/utils/ScanUtils.java
src/test/java/com/checkmarx/flow/controller/FlowControllerTest.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sast/config/OverwritingProjectConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/ScaCommonSteps.java
src/test/java/com/checkmarx/flow/utils/ScanUtilsTest.java

Implemented using common filtering mechanism for SCA, instead of custom logic. The changes are based on new CxSDK and CxGo SDK functionality.
Work item [299](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/299/)
Test scenario is defined in scanResultsProcessing.feature: "Apply filter severity and filter score on SCA results".

SCA filtering improvement

---

src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature

1. If bug tracker set to Json/CSV/XML and the directory path mentioned in application.yml doesn't exist cx-flow app will create a new directory path before file creation.
- In case the directory path already exists none will happen.  
2. Fix SCA cli scan test - Due to SCA scan update expected issue count set to 55
issue 1
src/main/java/com/checkmarx/flow/custom/CsvIssueTracker.java
src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
src/main/java/com/checkmarx/flow/custom/JsonIssueTracker.java
issue 2 
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature

Create directory path if not exist + Fix SCA cli scan test

---

src/main/java/com/checkmarx/flow/config/SarifProperties.java
src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java

Based on the current implementation, SARIF report is generated only for SAST scans and not for SCA results. The modified code adds this feature to generate the SARIF report for SCA scans as well.
Modified files:
src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
src/main/java/com/checkmarx/flow/config/SarifProperties.java
Screenshots of the issues when the cx.sarif file is uploaded in github:

Pr feature/sarif sca

---

src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java

A key/value pair in "additionalMetadata" was not being set before checking for config-as-code file in the BB Server repository.
Fixes #480
Performed a push event using BB server to verify it will consume the c-a-c file.

Fix for config-as-code broken for BB server push events (#481)

---

src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java

Fix misleading hints in cxflow logs when team creation failed in CxSAST
#447 
manual tests to verify new format
end to end automation and integration tests pass

"fix wrong hints in log message when team creation fail

---

src/main/java/com/checkmarx/flow/utils/HTMLHelper.java

Fixing null pointer exception when CxGo SCA results finding doesn't have version field

fix null pointer exception when SCA version is null

---

.github/PULL_REQUEST_TEMPLATE.md
src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
src/main/java/com/checkmarx/flow/service/GitHubService.java

Logic was missing to incorporate GitHub App authentication for GitHub Issues Integration.  This PR has updated the logic to include this support.
Fixes #511 
Testing was conducted using published GitHub App for kmcdon83/DVWA

Add GitHub App Support for GitHub Issues

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/test/java/com/checkmarx/flow/cucumber/component/batch/BatchComponentSteps.java

Adding logs to show cx-flow version during startup
Fixes #462 
Output from test run:
```
2020-11-09 22:38:56.587  INFO 87043 --- [  restartedMain] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService
2020-11-09 22:38:56.587  INFO 87043 --- [  restartedMain] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService 'webHook'
2020-11-09 22:38:56.656  INFO 87043 --- [  restartedMain] …
```

Adding BuildInfo Bean to add log entry on program launch

---

src/main/java/com/checkmarx/flow/config/GitLabProperties.java
src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java
src/test/java/com/checkmarx/flow/cucumber/integration/ast/scans/AstRemoteRepoScanSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cli/ast/AstCliSteps.java

Added changes to populate the Dependency scanning vulnerabilities from SCA in GitLab Security Dashboard.
All the vulnerabilities are shown as Dependency Scanning component and also in the Dependency List Tab

Support SCA Results in GitLab Security Dashboard

---

build-11.gradle
build.gradle
docs/Configuration.md

Update logic to only create/update scan settings and file exclusions on initial project creation or if the settings-override is set to true (default is false)
```
checkmarx
...
settings-override: true #default false if not provided
```
Fix issue #459

update sdk version and update wiki page

---

src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

Fixing scan configuration override
Expected behavior:
when adding 'engineConfiguration' value to config-as-code file, CxFlow should override global configuration and use value from config file
Fix: #549
see Config as code [wiki page](https://github.com/checkmarx-ltd/cx-flow/wiki/Config-As-Code)

fix engine configuration override

---

src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java

> Fixed an issue occurring while Sarif report generation from CxGo results where null values were found in the result.
Added default text for such null values.
> No issue was logged.
> Manual Testing was done using GitHub Actions.

Fixed an null value issue with Sarif report generation for CxGo.

---

src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/test/java/com/checkmarx/flow/cucumber/common/repoServiceMockers/GithubServiceMocker.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfig/CxConfigSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxconfigbugtracker/CxConfigBugTrackerSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java

Changing where GitHub Event grabs the Namespace (owner) value
Fixes #555 
Manual testing with forks and non-fork PRs.
E2E Tests

Fix namespace/owner value for Forked Repo

---

build.gradle
src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java

Fixed by excluding a transitive dependency on log4j used by ConfigProvider.
Related work item: [359](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/359/).

Fix for #566: Log initialization error during CxFlow startup

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java

when executing cxflow via command line, and using pull/merge request as bug-tracker, vulnerabilities lines not filled and pointing to null.
Fixed by adding repo url to scan request so cxflow can calculate the correct link
Fix issue #527 
CxFlow CLI-Integration-Tests

Fix vulnerability line links in merge/pull request

---

src/main/java/com/checkmarx/flow/service/JiraService.java
src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
src/main/java/com/checkmarx/flow/utils/ScanUtils.java

> Fixed bug 335: Cx-Go SCM tickets are always opened with 'new' status
> https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/335

Fixed bug 335: Cx-Go SCM tickets are always opened with 'new' status

---

src/main/java/com/checkmarx/flow/controller/ADOController.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/controller/GitLabController.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/ReposManagerService.java
src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java

When a GitLab webhook request arrives, CxFlow now uses the `project.path_with_namespace` field from the request to extract organization ID and send it to ReposManager. Previously the `project.namespace` field was used. This was problematic, since the  `project.namespace` field is only intended for display purposes.
Example: suppose project.path_with_namespace is `group1/subgroup1/my-project`
Then organization ID sent to ReposManager will be `group1`
User story [364](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/364/). 
Tested manually with 
- project inside a top-level group
- project inside a subgroup
- group and project names containing spaces
In the future, cxIntegrations.feature should be expanded to include these tests.

Passing GitLab group path as organization ID to ReposManager

---

Dockerfile

> Duplicate the 'apk upgrade' command to avoid compatibility java issue inside the docker.
A bug reference link: https://github.com/opencb/opencga/issues/1653

Duplicate the apk upgrade command

---

src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/CodeBashingService.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/JiraService.java
src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
src/main/java/com/checkmarx/flow/utils/ScanUtils.java
src/test/java/com/checkmarx/flow/cucumber/component/cxintegrations/CxIntegrationSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/bugtrackers/ado/ScaIssuesCreationSteps.java
src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature

> This bug fixes a scenario when SCA has multiple identical packages name path, which one package has a fix version and the other one doesn't have. cx-flow gets the package name within the results, and since there are more than 1 identical package, it picks one of them. The inconsistency with the package's version causes cx-flow relate the result differently each time when it tries to update/close a ticket.
Example:
> [Bug-issue](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/487)

Fix SCA open, update & close tickets mechanism

---

build-11.gradle
build.gradle

> Upgrade SDK version to 0.4.77: Support SCA scan with cx-origin header
> [User Story URL](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/495)
Manual testing were performed and new scan header has being validated by Fadi from SCA.

Upgrade SDK version to 0.4.77: Support SCA scan with cx-origin header

---

src/main/java/com/checkmarx/flow/controller/GitLabController.java
src/main/java/com/checkmarx/flow/dto/RepoComment.java
src/main/java/com/checkmarx/flow/dto/gitlab/Comment.java
src/main/java/com/checkmarx/flow/dto/gitlab/ObjectAttributes.java
src/main/java/com/checkmarx/flow/dto/gitlab/Project.java
src/main/java/com/checkmarx/flow/dto/gitlab/Repository.java
src/main/java/com/checkmarx/flow/dto/gitlab/User.java
src/main/java/com/checkmarx/flow/exception/GitLabClientRuntimeException.java
src/main/java/com/checkmarx/flow/service/BitBucketService.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/GitLabService.java
src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
src/main/java/com/checkmarx/flow/service/RepoService.java
src/main/java/com/checkmarx/flow/service/ResultsService.java
src/test/java/com/checkmarx/flow/cucumber/integration/pullrequest/updatecomments/UpdatePullRequestCommentsSteps.java
src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature

Description
User story 129:
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/129
Gitlab - Reduced comments notifications on pull requests + Tests
Testing
Gitlab new scenarios covered by tests
First, create a new merge request scan (SAST, SCA, and Both), add comments, and verify they exist.
Second create a new merge request scan (SAST, SCA, and Both), add comments, and verify they exist then commit another change to the previous merge request, update comments and verify comments are updated.
Checklist

Gitlab - Reduced comments notifications on pull requests + Tests

---

.circleci/config.yml
src/main/java/com/checkmarx/flow/service/JiraService.java

On batch mode CxFlow attempting to modify a map on multiple threads to add the custom_fields for Jira into it. Since they are all using the same Jira service, The code is trying to modify data on multiple threads with no protection.
https://github.com/checkmarx-ltd/cx-flow/issues/603

Prevent ConcurrentModificationException error while execute batch mode

---

build-11.gradle
build.gradle
docs/Integration-with-CxSCA.md
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/RunSCATeamsSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
src/test/resources/cucumber/features/integrationTests/sca/teams.feature

> Support SCA project teams assignment when a new project is being created.
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/495)
> Both positive & negative integration tests were added. The positive tests validate the new team assignment and the negative one validates an error is getting occur while trying to assign not existing team to a project.

Support SCA project teams assignment

---

build-11.gradle
build.gradle
docs/Integration-with-CxSCA.md
src/main/java/com/checkmarx/flow/service/SCAScanner.java
src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java

Additional configuration in SCA zip scan flow - Include source files
Default value set to false, In order to change the default CxFlow SCA zip scan behavior this property, should be added underneath the SCA configuration section:
includeSources: true

Support include source files option for SCA zip scan

---

src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java
src/main/java/com/checkmarx/flow/service/ReposManagerService.java

Previously, to get CxGo config from CxIntegrations, the following data was sent to the CxIntegrations API: 
- SCM type ("gitlab", "bitbucket" etc.)
- SCM organization id
Now, on-premise SCM support was added to CxIntegrations. This means that we no longer can send SCM type to CxIntegrations. E.g. there can be several "bitbuckets". Instead, we are now sending
- repository URL, as used in 'git clone'
- SCM organization id - same as previously
Using these 2 parameters, CxIntegrations can figure out which SCM instance CxFlow is asking about.
Work item [366](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/366/).
Depends on [this PR](https://github.com/checkmarx-ltd/Integrations-ReposManager/pull/35).
Tested manually with several kinds of cloud-based SCMs. It's not possible to test the new …

Support on-premise SCMs in CxIntegrations calls

---

build-11.gradle
build.gradle
docs/Integration-with-CxSCA.md
src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
src/test/java/com/checkmarx/flow/cucumber/integration/sca_scanner/teams/SCATeamsSteps.java
src/test/resources/cucumber/features/integrationTests/cli/astCliScan.feature

> Config as code now also supports team assignment within SCA section
#634 
> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/540)
>Manual tests were performed.

Support SCA team assignment within config-as-code

---

build-11.gradle
build.gradle
src/test/java/com/checkmarx/flow/cucumber/component/parse/LoadingSastResultsSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/parse/RunningCxFlowSteps.java
src/test/java/com/checkmarx/flow/cucumber/component/parse/VerifyingCxFlowReportSteps.java
src/test/java/com/checkmarx/flow/cucumber/integration/cxgo/CxGoRemoteRepoScanSteps.java
src/test/resources/cucumber/data/cxflow-reference-reports/2-findings-different-severity.json
src/test/resources/cucumber/data/sample-sast-results/1-finding-custom-severity.xml
src/test/resources/cucumber/features/componentTests/parse.feature

Added a test scenario that checks if we use the right severity during filtering.
Work item [531](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/531/).
The new scenario verifies a CxSDK change, as of https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/99.
The new scenario was added to test\resources\cucumber\features\componentTests\parse.feature

Added a test scenario for severity filter

---

templates/gitlab/v2/Checkmarx.gitlab-ci.yml

Issue with quotes cause two jobs to run in the pipelin
A misplaced single quote was causing two pipelines to run.
N/A
Manual GitLab tests

Fixed misplaced single quotation

---

docs/CxSCA-Integration.md
src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
src/test/resources/cucumber/features/integrationTests/cxgo/cxgoScanProcessing.feature
src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature

> Until now, it was impossible to override a specific fields via config as code for SCA scans.   
> [JIRA user story URL](https://checkmarx.atlassian.net/browse/AST-1520)
Manual test were conducted

SCA config as code required all fields to be define

---

docs/Configuration.md

This PR updates the CxFlow documentation to reflect a proposed change to the Checkmarx Spring Boot Java SDK to support custom result states. The change to the SDK is currently being reviewed.
The SDK PR: https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/142
Adding a custom result state: https://checkmarx.atlassian.net/wiki/spaces/PTS/pages/734887937/Add%2Ba%2Bcustom%2Bresult%2Bstate
I have tested the …

Document configuration for custom result states

---

src/main/java/com/checkmarx/flow/service/JiraService.java
src/test/resources/cucumber/features/integrationTests/pull-request-comments-update.feature

This fixes the problem with SCA JIRA issues not updating its priority when it changes on the CxSAST side.
Added extra debugging messages to increase JIRA configs visibility to improve logging of JIRA issues updates and issues closure when the issue is not in the vulnerabilities results list from CxSAST/CxSCA.
Fixes #783 
This was tested by running a scan against an empty JIRA project with CxSAST and CxSCA configured, the issues were created, then the priority of the tickets were changed manually on JIRA, then CxFlow was executed again to run the scan on both products and the JIRA issues' priorities were restored.

Fix JIRA issue priority not updating for SCA

---

src/main/java/com/checkmarx/flow/service/JiraService.java

Fix colon ':' char being replaced by an underscore '_' when setting a JIRA label field, this can affect the ability of setting values in a label with colons.
N/A
This change was tested using a JIRA field of 'static' type, using `jira-default-value` as a list of labels like the ones applied to the `Labels` JIRA issue field.
Described in #800.

Fix colon not allowed in JIRA issue label

---

build-11.gradle
build.gradle
docs/CxSCA-Integration.md
src/main/resources/application-sca.yml
src/test/resources/application.yml

> This PR adds scan-timeout feature in sca scanning. scan-timeout should be added in application.yml under sca. If not default timeout will be 120 mins
> In order to test Scan TimeOut for SCA, the configuration property should be added underneath the sca configuration section.
scan-timeout: 120

updated CxSBSDK version to support scascantimeout

---

docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/config/JiraProperties.java
src/main/java/com/checkmarx/flow/service/JiraService.java
src/main/java/com/checkmarx/flow/utils/HTMLHelper.java

> Added label-prefix property for JIRA which will allow user to use a custom issue prefix for their JIRA issues and if not provided it will use the default issue prefix value of "CX". 
> Manually tested this feature 
>  1. When a label-prefix is set Jira creates issues with the provided label-prefix for that project.
> 2. When the label-prefix value is changed for the same project, Jira creates new issues with newly …

Jira custom issue prefix feature

---

src/main/java/com/checkmarx/flow/service/JiraService.java

Fix hyphen '-' char not to be replaced by an underscore '_' when setting a JIRA label field, this can affect the ability of setting values in a label with hyphens.
N/A
This change was tested using a JIRA field of 'static' type, using `jira-default-value` as a list of labels like the ones applied to the `Labels` JIRA issue field.
Described in #825.

Fix hyphen not allowed in JIRA issue label

---

src/main/java/com/checkmarx/flow/service/ADOService.java
src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java

> This PR solves the issue of ADO PR status stuck on wait if a PR is created for a project for which there is already a scan running. 
>1.If scan is running for a project and a PR is opened for same project
a.	 a thread is created with message “Scan not submitted to Checkmarx due to existing Active scan for the same project.” And its status is changed from “Active” to “Closed”. 
>b.	And the status of the PR is changed to …

fix for ado pr status stuck on waiting

---

docs/Bug-Trackers-and-Feedback-Channels.md
docs/Configuration.md
src/main/java/com/checkmarx/flow/config/JiraProperties.java
src/main/java/com/checkmarx/flow/constants/JiraConstants.java
src/main/java/com/checkmarx/flow/service/JiraService.java

> This pull request adds the ability to specify, via configuration, the format of the Jira issue summary for Jira issues raised for SAST results. The Jira issue summary acts as an implicit grouping operator for SAST results; this change allows users to change this grouping. The concrete use case is a customer who wants separate Jira issues for results with different severities (the customer's triage process includes …

Custom Jira Summary feature

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/utils/ScanUtils.java

This PR Fixes AB#605 . SCA reported vulnerabilities that are marked ignored in SCA, were still considered as valid/open vulnerabilities.  CxFlow JIRA handling supported handling of FALSE positives for SAST but not for SCA. Most logic is same. The missing part of SCA specific logic to count false positives and to check if all findings in a issue are false positives. 
Now, CxFlow closes the JIRA issue if the corresponding vulnerability received in SCA report is marked ignored.
ADO WorkItem AB#605
Perform SCA scan on a project with JIRA as bug tracker . Issues will be created for vulnerabilities reported.
Triage vulnerabilities in SCA to mark some of them ignored.
Perform SCA scan again on same project. 
Validated that JIRA issues corresponding to the ignored vulnerabilities are marked as …

False positive handling for SCA

---

build-11.gradle
build.gradle
docs/Config-As-Code.md
docs/Configuration.md
src/main/java/com/checkmarx/flow/config/FlowProperties.java
src/main/java/com/checkmarx/flow/dto/FlowOverride.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

> This PR adds feature to provide ssh support per project. 
|ssh-key-list(map   in application.yml in checkmarx section):      sshtest: id_rsa      sshtest2: .ssh/pk2      sshKeyIdentifier(in cx.config): "sshtest"      ssh-key(string in application.yml in checkmarx section): empty | ssh-key-list(map in   application.yml in checkmarx section):     empty      sshKeyIdentifier(in cx.config): "sshtest"      ssh-key(string in …

Feature for ssh support per project

---

Dockerfile
src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/GitHubApiHandler.java
src/test/java/com/checkmarx/flow/cucumber/integration/end2end/genericendtoend/Repository.java

To fix vulnerabilities reported on the docker image. 
https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/602/
Created local docker images for Java8, Java11 and Cxgo. Ran those through tools like grype and trivy. The only reported vulnerabilities are related to CxFlow library dependencies, which are related to ant and antlr. These same vulns are also reported by SCA on CxFlow library dependencies.  There is tracking bug already open on the board .
- [ NA] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ Y] All active GitHub checks for tests, formatting, and security are passing
- [Y ] The correct base branch is being used

Base alpine used instead of one from openjdk

---

build-11.gradle
build.gradle
docs/Config-As-Code.md
docs/Configuration.md
docs/Execution.md
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

This PR enables support for project-level custom fields. Project-level custom fields can be specified either on the command line, using the new --project-custom-field command line option, or via the cx.config config-as-code file (which is now also used in batch mode when processing local source code.
Aha!: https://checkmarx1.aha.io/features/SDLC-301
GitHub: https://github.com/checkmarx-ltd/cx-flow/issues/730
I have …

Enable project-level custom fields

---

build-11.gradle
build.gradle
docs/Config-As-Code.md
docs/Execution.md
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

This PR adds support for scan-level custom fields to CxFlow. Scan-level custom fields can be specified either via the command line, using the new `--scan-custom-field` option, or via a `cx.config` config-as-code file.
Aha! entry: https://checkmarx1.aha.io/features/SDLC-350
GitHub issue: https://github.com/checkmarx-ltd/cx-flow/issues/873
I have tested this using a bespoke test harness written in Python. I will push the …

Pr enable scan level custom fields

---

docs/External-Scripts.md
src/main/resources/samples/ScanComment.groovy

Add `ScanComment.groovy` sample script to add repo URL, branch and commit id/hash to the scan-comment.
Update `docs/External-Scripts.md` markdown file to use relative links so the files point to the branches documentation.
Fix wrong configuration property for `branch-script`, it's now corrected to `cx-flow.branch-script` instead of `checkmarx.branch-script`.
N/A
This change was tested with CxFlow's server running with the sample Groovy file on the server root directory and observing CxSAST scan comments being changed after scans triggered through CxFlow.

Add scan comment sample script

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java

This PR fixes Log4j CVE in CxFlow for both java8 and java 11 version of cxflow artifact.
CVE-2021-44228
1. Verified that cxflow functionality working
2. Scanned cxflow for both java8 build.gradle and build-11.gradle
Java11 - https://sca.checkmarx.net/#/projects/812d6aa9-3ce5-49df-bc31-7a6bd2858fb6/reports/32613414-d4c4-46fb-82c8-34f9245c9e7b/packages/all
Java 8 - https://sca.checkmarx.net/#/projects/2202e81a-67c0-40c3-95cf-cf34bb223659/reports/704befdb-44dc-4890-8467-4ca20ca5397f/packages/all
- [NA ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [Y] All active GitHub checks for tests, formatting, and security are passing
- [Y ] The correct base branch is …

Log4j 2.16.0 uptake in java8 and java11 build gradle

---

Dockerfile
docs/Execution.md

This PR provides the support to give JVM options for Heap Memory Size using the JAVA_OPTS ENV variable. If it is not provided then a default value of Xms512m and Xmx2048m will be used.
When   JAVA_OPTS not provided      during docker run | When JAVA_OPTS="-Xms512m   -Xmx9216m"      was provided durnig docker run | When   JAVA_OPTS="-XshowSettings:vm"      was provided …

Support for providing Min-Max Heap size for docker

---

src/main/java/com/checkmarx/flow/config/SarifProperties.java
src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java

- Link to SAST Result
- Correct the Mapping of Security Severity as below:
Over 9.0 is critical, 7.0 to 8.9 is high, 4.0 to 6.9 is medium and 3.9 or less is low.
- Check for empty value in Description and Line Number and populate default value.
> Describe how …

[ADO 587] Link to SAST Result and Check for Empty Value In Description

---

src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java

PR #857 (added scanQueuing and scanQueuingTimeout  size/M) overridden by
PR #884 (Add scanResubmit property to config-as-code)
If checkmarx.scan-queuing is true then Submit the new scan Request. If checkmarx.scan-queuing is false (Default Value) then check for scan resubmit and Process the request accordingly.
Set checkmarx.scan-queuing to true.
Run cx-flow in web hook …

Scan Queuing Change from PR #857 (added scanQueuing and scanQueuingTimeout  size/M)

---

docs/Configuration.md
src/main/java/com/checkmarx/flow/service/EmailService.java

When `cx-flow.mail.notification` is `true` and `cx-flow.mail.cc` is not defined or empty, we have a NullPointerException. 
https://github.com/checkmarx-ltd/cx-flow/issues/753
Use this configuration:
```yaml
cx-flow:
token: xxxx
bug-tracker: Json
bug-tracker-impl:
- CxXml
- Json
- JIRA
- GitLab
- GitHub
- Csv
- Azure
- Rally
- ServiceNow
- Sarif
branches:
- develop
- master
- security
filter-severity:
- High
filter-category:
filter-cwe:
filter-status:
mitre-url: https://cwe.mitre.org/data/definitions/%s.html
jira-project-field: jira-project
jira-issuetype-field: jira-issuetype
jira-custom-field: jira-fields
jira-assignee-field: jira-assignee
mail:
host: your-smtp.com
port: 2525
username: your-user
password: your-password
enabled: true
notification: true
```

When cx-flow.mail.cc is not set, NullPointerException

---

src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

> This PR fixes null pointer exception when reponame and branch name is not provided in cli mode and cxconfig contains override for project name.
> Tested by providing override for project name in CxConfig and provided --app during CLI execution and null pointer exception does not occur

fixed null pointer exception in ConfigurationOverrider

---

docs/CodeBashing.md
src/main/java/com/checkmarx/flow/service/JiraService.java

[JIRA CXFLW-100] Update CodeBashing API and documentation in Wiki
Update Codebashing document to provide configuration in application.yml file which will add code bashing url / lessons to Jira Tickets
Update the code to provide the code bashing lessons (not the base url for code bashing ) in the Issue raised in Jira by CxFlow. 
[> Include supporting link to GitHub Issue/PR number …

[JIRA CXFLW-100] Update CodeBashing API and documentation in Wiki

---

docs/Delete-Branch.md
src/main/java/com/checkmarx/flow/controller/bitbucket/server/BitbucketServerController.java

> This PR adds feature to delete project in CxSAST when an unprotected branch is deleted in BitBucket server
> Configured CxFlow with Bitbucket server(on-prem) and created a PR which created project with name JavaVulnerabilityLabE-branch-name.
> In CxSAST the count of total used projects incremented by 1.
> When branch was deleted from Bitbucket server PUSH event with type DELETE was fired and DELETE event was handled.
> …

Pr bitbucket delete event support

---

build-11.gradle
build.gradle
docs/Bug-Trackers-and-Feedback-Channels.md
docs/CxSCA-Integration.md
src/main/java/com/checkmarx/flow/custom/CxXMLIssueTracker.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java

> This PR adds support for retrieving CxSCA risk report in XML format when bug tracker is set as CxXML. 
- SCA --project mode (should create 1 file with sca risk report)
- SAST --project mode (should create 1 file with sast report)
- SCA --scan mode (should create 1 file with sca risk report)
- SAST --scan mode (should create 1 file with sast report)
- SCA --web mode (should create 1 file with sca risk report)
- SAST …

Feature for CxXML as bug-tracker for CxSCA

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/config/CliMode.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/service/JiraService.java

- For bug tracker as Jira, Create the issue in Jira with Label as SAST scanner and SCA scanner after the scan.
- Filter the issue on bases of type of scan (SCA or SAST) and Update/Open/Close the issue for which scan is initiated for the project.
- If scan is initiated for both SCA and SAST then issues for both type of scan will be update for that project.
> [Include supporting link to GitHub Issue/PR …

Issues in Jira should not be closed on re-run of other/alternate scan for same project.

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/ASTScanner.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java

Description:
Parse mode suport for SCA product in CX-Flow.Now we can use --parse mode in cx-flow and create the issue on different bug tracker(like Jira,Json,Sarif etc).
References:
https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/205
Testing:
Below are the test case:
A]
Generate report from ScaResolver tool and use this report in parse mode command execution.
B]
Step 1: run scan mode
run the scan command  through CLI(i.e from cmd) and generate scan report on sca portal.
Use below  scan command:-
java -jar cx-flow-1.6.31.jar --spring.config.location="<location of your application.yml>" --scan --f="<location of your  cx-flow>" --cx-team= "CxServer" --cx-project="<project name>" --app="<app name>"
Step2:
From sca portal export the scan report in xml format. 
Step 3:parse …

Pr parse mode implementation for sca

---

src/main/java/com/checkmarx/flow/dto/azure/Repository.java

Scan failing due to value of size variable of Azure Repository is large
If Repository is very large then request webhook size variable value does not fit in Integer data type.
Changing the data type to Long in "com.checkmarx.flow.dto.azure.Repository" to accommodate larger value. 
> Describe how this change was tested. Be specific about anything not tested and reasons …

Scan failing due to value of size variable of Azure Repository is large

---

templates/gitlab/v3/Checkmarx.gitlab-ci.yml

Use project for scanning single project instead of all the projects in the teams namespace
support issue: 00105865
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and …

update gitlab template

---

src/main/java/com/checkmarx/flow/controller/FlowController.java
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java

Extra fields existed in the Scan Comments for a "PostBack" scan.  Those fields were not recognized by the Postback Parser on the `/postbackAction` endpoint.  The missing fields were added and tested.
Also, the Postback mode report generation does not use the GitHub App.  Fields were added to the scan comments to pass the installation id so that CxFlow can post as the GitHub app.
Fix postback - Re: Issue #939 
Testing was …

Fix postback Scan Reports

---

docs/Bug-Trackers-and-Feedback-Channels.md
docs/Configuration.md
src/main/java/com/checkmarx/flow/config/JiraProperties.java
src/main/java/com/checkmarx/flow/service/JiraService.java

A new property has been added to the `JiraProperties` class: `suppressCodeSnippets`. This property is a list of vulnerability names for which code snippets should not be generated when creating a Jira ticket.
The rationale behind this is that some code snippets can contain sensitive information (e.g., hard-coded …

Support suppression of code snippets for Jira tickets

---

src/main/java/com/checkmarx/flow/custom/GitLabSecurityDashboard.java

When you use Gitlab Security Dashboard reports it gives a warning at the moment:
> :warning: Warning parsing security reports
Check the messages generated while parsing the following security reports, as they may prevent the results from being ingested by GitLab. Ensure the security report conforms to a supported [JSON Schema](https://docs.gitlab.com/ee/development/integrations/secure.html#report).
checkmarx-scan-security-dashboard-on-mr (1)
[Schema] property '/version' is not of type: string

Gitlab Security Reports is expecting a string instead of a float

---

docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/service/JiraService.java

Jira statuses are not case-sensitive: you cannot have two distinct statuses whose names differ only by case. Furthermore, in its UI, Jira displays the statuses in uppercase but the Jira API does not. E.g., the "In progress" status will be displayed in the UI as "IN PROGRESS" but the API will return "In Progress". This makes it easy for a customer to misconfigure CxFlow as the natural approach is to use the value from the …

Pr case insensitive jira statuses

---

.circleci/config.yml

Pipeline is failing to create eks cluster . This issue is said to be known issue with default kubectl version, which got upgraded to 1.24.0 and it has issues. 
To fix, disabled auto kubectl installation as part of the aws-eks/update-kubeconfig-with-authenticator and added explcit kubectl-install step.  ORB version used does not support simply specifying kubectl-version on update-kubeconfig-with-authenticator.
Additionally, it is suggested to delete default kubectl config. To do this, aws cli installation and aws eks delete command is added.
N/A
Verified that when version is changed to 1.23.0 for the deploy-cxflow step, the pipeline worked.
N/A

fixed pipeline kubernetes issue

---

build-11.gradle
build.gradle
docs/Config-As-Code.md
docs/Configuration.md
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

This PR allows CxFlow to configure the recipients of after/before/failed scan emails for SAST scans. The notifications can be configured via the `application.yml` file (and, by extension, the command line and via environment variables) or via config-as-code. If both are present, the config-as-code configuration …

Add support for after/before/failed scan email notifications

---

docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/service/JiraService.java

> This PR fixes the issue of JIRA issues changing statuses when closed and reopened when ran in --project mode.
Mode of   Scanning with JIRA BT | Enabled scanners | Initial conditions | Results
-- | -- | -- | --
SCAN | SAST,SCA | No Issues present in JIRA for        any of the scanners(i.e empty project) | 1. Scan initiated for both the   scanners and once completed results were generated.     2. Based on the results …

[JIRA:CXFLW-391]Fixed issue closing and reopening in JIRA

---

build-11.gradle
build.gradle

- Resolves https://github.com/checkmarx-ltd/cx-flow/issues/1025: `java.lang.NoClassDefFoundError: ognl/DefaultMemberAccess`
https://github.com/checkmarx-ltd/cx-flow/issues/1025 and https://github.com/thymeleaf/thymeleaf-spring/issues/203
Just run CxFlow 1.6.34 with Java 8, in server mode, with an application.yml having cx-flow-mail defined with either SMTP parameters, or a Sendgrid API key.

Downgrading OGNL due to https://github.com/thymeleaf/thymeleaf-spring/issues/203

---

docs/Config-As-Code.md
src/main/java/com/checkmarx/flow/dto/FlowOverride.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
src/main/java/com/checkmarx/flow/service/ConfigurationOverrider.java

Support the specifying of the `zip-exclude` property via config-as-code. Addresses issue #1043.
- Add a `zipExclude` property to the `FlowOverride` class.
- Add a `zipExclude` property to the `ScanRequest` class.
- Update the `AbstractVulnerabilityScanner` class to use the `request`'s `zipExclude` property, if present.
- Update the `ConfigurationOverrider` class to set the `ScanRequest`'s `zipExclude` property to the …

Allow zip exclude via config as code

---

src/main/java/com/checkmarx/flow/service/IssueService.java
src/test/resources/cucumber/features/integrationTests/cli/scaCliScan.feature
src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature

> This PR fixes the issue of bug trackers closing and then reopening issues. When initially both scanners were enabled and issues were created and then consecutive scan was done with only one scanner then the issues of other scanner were closed this is fixed. 
> Manually tested all the bug trackers like ADO, GitLab, and GitHub and the issues of one scanner were not closing when a scan with other scanner was initiated.

Fixed closing and reopening of issues for all bug trackers

---

.circleci/config.yml
docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/config/FlowProperties.java
src/main/java/com/checkmarx/flow/service/EmailService.java
src/main/resources/application.yml

Implementing option to disable certain notifications when:
- Client doesn't want to receive a "Scan Submitted" e-mail;
- Client doesn't want to receive a "Scan Summary" e-mail with empty results.
This was requested by a client.
N/A
Set the following variables either using environment variables, command-line arguments or `application.yml`:
```yaml
cx-flow:
mail:
notification: true # if this is set to false, all the settings below are disregarded.
enabled-notifications:
scan-submitted: true # the default is `true`
scan-summary: true # the default is `true`
scan-summary-with-empty-results: false # the default is `true`
```

E-mail Notifications Configuration Toggles

---

.circleci/config.yml
src/main/java/com/checkmarx/flow/utils/ZipUtils.java

Change the log level for the messages which show when a file has been matched, when checking for zip file exclusions, from `DEBUG` to `TRACE`. The rationale is to prevent excessively large logs, especially when scanning Node.js projects for which the `node_modules` folder has been excluded.
> Include supporting …

Log zip-file exclusions at the TRACE level

---

src/main/java/com/checkmarx/flow/service/JiraService.java

When running CxFlow with
enabled-vulnerability-scanners:
- SCA
- SAST
and teams are different between SCA and SAST
sca:
team: "/CxServer/sast"
checkmarx:
team: /CxServer/sca
SCA tickets in Jira contains
Cx-Team: /CxServer/sast"
Instead, if only running SCA, SCA Jira tickets do not contain any Cx-Team data (i.e. Cx-Team does not appear)
https://github.com/checkmarx-ltd/cx-flow/issues/1033

CXFLW-540 Fixed Jira team issue for sca

---

docs/Configuration.md
src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java

The default 'create issue' API in GitHub is very strict about rate limits. We consistently get a 'secondary rate limit error' after creating ~20 issues. To avoid the error, we need to make a ~3s delay between requests.
Tested on SAST 9.4 with bug Tracker as GitHub

Pr cxflw 175 secondary rate limit

---

docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/service/EmailService.java

Client asked to remove lows and mediums from summary e-mail. 
N/A
Set the following variables either using environment variables, command-line arguments or `application.yml`:
```yaml
cx-flow:
mail:
notification: true # if this is set to false, all the settings below are disregarded.
enabled-notifications:
scan-submitted: true # the default is `true`
scan-summary: true # the default is `true`
scan-summary-with-empty-results: false # the default is `true`
```
Make sure to scan a project that have no highs and mediums, and then another project that has highs and mediums.

Disregarding Lows and Infos for the e-mail summary.

---

build-11.gradle
build.gradle
docs/CxSCA-Integration.md
src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java
src/test/resources/cucumber/features/integrationTests/sca/scanResultsProcessing.feature

--cxprojectname parameter can be overridden by property( "expPathSastProjectName": "OverrideProjectName")provided in sca section of config-as-code(cx.config) file. also added unique folder name.

Added Config as code for SCA Resolver

---

src/main/java/com/checkmarx/flow/controller/GitLabController.java

Fixed endless loops of scan during gitlab merge request.
#1079
Manual Testing using Gitlab Merge Request using sast and sca.

CXFLW-573 GitLab merge requests create an endless loop of scans #1079

---

docs/Prerequisites-and-Requirements.md
src/main/java/com/checkmarx/flow/config/FlowConfig.java
src/main/java/com/checkmarx/flow/config/JiraProperties.java
src/main/java/com/checkmarx/flow/jira9X/FieldSchema.java
src/main/java/com/checkmarx/flow/jira9X/IssueFields.java
src/main/java/com/checkmarx/flow/jira9X/IssueType.java
src/main/java/com/checkmarx/flow/jira9X/Project.java
src/main/java/com/checkmarx/flow/jira9X/StandardOperation.java
src/main/java/com/checkmarx/flow/service/JiraService.java

/rest/api/2/issue/createmeta Endpoint for Jira Rest Client has been deprecated from 8.4 version.  New Endpoints are
Return the list of projects 
/rest/api/2/project  
Return a list of issuetypes given in project
/rest/api/2/issue/createmeta/{projectIdOrKey}/issuetypes 
Return a list of fields given a project and issuetype
/rest/api/2/issue/createmeta/{projectIdOrKey}/issuetypes/{issueTypeId} 
[> Include supporting link to GitHub Issue/PR number](https://github.com/checkmarx-ltd/cx-flow/issues/1082)
Tested on Jira 9.2.0 Server

Jira 9 support added

---

Dockerfile
docs/Execution.md
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/dto/ScanRequest.java
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java

Async behavior can be achieved by setting bug tracker as NONE but there was no way to get scanId for specific project hence added scanId parameter for project mode 
example:
```
java -jar cx-flow-<ver>.jar \
--project \
--scanId=<unique scanId>
--cx-team="CxServer/SP/Checkmarx/Test" \
--cx-project="riches-main" \
--app=AppName
```
https://github.com/checkmarx-ltd/cx-flow/issues/969

Added scan id CLI parameter for project mode

---

src/main/java/com/checkmarx/flow/CxFlowRunner.java

GitLab CI/CD provides extra token in repoUrl. due to which code break while updating source.

Fixed GitLab CI/CD repoUrl Creation 

---

docs/Configuration.md

This pull request documents two properties that were added to the Checkmarx Spring Boot Java SDK as part of this pull request: https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/279.
The properties are:
- `project-branching-check-count`
- `project-branching-check-interval`
See https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/issues/278
> Describe how this change was tested. Be specific …

Document properties for the waiting for branching to complete

---

docs/Bug-Trackers-and-Feedback-Channels.md
docs/CxSCA-Integration.md
src/main/java/com/checkmarx/flow/service/JiraService.java

Changed sca-resolver-add-parameters from String to Map
example :
sca-resolver-add-parameters :
log-level : Debug
e : "*.ext1"
custom-parameter : "--gradle-parameters='USERNAME=abc PASSWORD=cba'"
Also added new parameters
enable-exploitable-path : true
sca-resolver-override-project-name : <ProjectNameToOverride>
#1133
#1132

ScaResolver addParams Fix

---

docs/Configuration.md

This PR documents the `restrict-results-to-branch` configuration property added to the Checkmarx Spring Boot Java SDK in pull request 286.
https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/286
> Describe how this change was tested. Be …

Document restrict-results-to-branch property.

---

build-11.gradle
build.gradle
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/JiraService.java
src/main/java/com/checkmarx/flow/service/ThresholdValidator.java
src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java

hen customer marks a vulnerability as "Not Exploitable" for SCA, it still causes the Threshold to trigger in CxFlow which breaks their build. 
This is creating an issue for the customer as they do not want these vulnerabilities to trigger the Threshold which is why they're marking them as Not Exploitable.
Steps to Reproduce
For direct dependency marks a vulnerability as "Not Exploitable" for SCA, it still causes the …

CXFLW-625 SCA scan failures with Threshold and DevDependencies Ticket No | 00144935

---

src/main/java/com/checkmarx/flow/utils/HTMLHelper.java

Often the time, it's found that the result summary table in the Gitlab Comment could be very long and make other comments hard to read. Because of that, It would be better to make the result summary collapsible.
None
The code and feature is pretty straightforward. I have generated a new build and all work as expected.

make result overview collapsible

---

docs/Running-CxFlow-as-a-Windows-Service.md

In step 4 <Argument > --web tag missing.
As Cx-Flow will run as windows service, only mode applicable is --web.

Running-CxFlow-as-a-Windows-Service documentation fix

---

docs/Configuration.md

Description
I am trying to get the value of the scan ID so I can use it with the Checkmarx API later in my Github Actions workflow.
The Github Actions has the following organization:
Each Github repository can setup one or more workflows. Each workflow is triggered in response to events that occur within the repository (e.g. pull requests, releases, manual invocation, etc.)
Each workflow contains one or more jobs. The jobs run parallelly in separate compute instances unless you setup dependencies between the jobs.
Each job contains one or more steps. The steps are run in sequence.
Each step can either be a shell script or a custom action. The step can take inputs and environment variables as well as produce named output values that can be referenced by future steps.
Checkmarx provides a …

CXFLW-753 Added Documentaition for scanID as output variable

---

src/main/resources/logback-spring.xml

The log masking pattern for tokens now stops at either whitespace or an ampersand (previously, it stopped only at whitespace). This means that text like:
token=abcdefg&foo=bar
Is masked as:
token=*******&foo=bar
Instead of:
token=***************
N/A
> Describe …

Tweak the log masking configuration

---

Dockerfile
src/main/java/com/checkmarx/flow/utils/ScanUtils.java

Issue seems to be with URL. JIRA taking incorrect URL.
JIRA Actual URL:
(https://eu.sca.checkmarx.net/#/projects/6f54c9aa-94fd-4eed-ab85-0e7a56a8a8f0/reports/f80e5846-200f-47b7-bd10-f0a986b3bcaf/vulnerabilities/CVE-2014-0107%3AMaven-xalan%3Aserializer-2.7.1/vulnerabilityDetails) 
Expected URL:
(https://eu.sca.checkmarx.net/#/projects/6f54c9aa-94fd-4eed-ab85-0e7a56a8a8f0/reports/f80e5846-200f-47b7-bd10-f0a986b3bcaf/vulnerabilities/CVE-2014-0107%3AMaven-xalan%3Aserializer-2.7.1/vulnerabilityDetailsGql)

Vulnerability URL fix for SCA 

---

docs/Thresholds-and-policies.md

Description
I am following "[AWS CodeBuild](https://checkmarx.com/resource/documents/en/34965-8206-aws-codebuild.html) " to trigger CxSAST scan from AWS CodeBuild. The CxSAST scan was triggered successfully, but there are two issues in related to thresholds: (1) I want the build to fail if high vul >=1 or medium vul >=1 or low vul >=10. The actual scan returns 0 high, 0 medium, and 3 low, but CxFlow still exit with code 10. It seems the build doesn't take my threshold into account. (2) I want the build fail when CxFlow exit with code 10. But in reality, even if CxFlow prints error in the log, the buildspec command still returns 0, thus made the build phase succeed.

CXFLW-829 Added Documentation for AWS buildspec

---

src/main/java/com/checkmarx/flow/utils/ScanUtils.java

Fixed NullPointerException for SCA methods
Methods name
- removePackageCurrentVersionFromPath
- getCurrentPackageVersion

Fixed NullPointerException for SCA methods

---

docs/Bug-Trackers-and-Feedback-Channels.md
src/main/java/com/checkmarx/flow/config/ADOProperties.java
src/main/java/com/checkmarx/flow/custom/ADOIssueTracker.java

Description
When using --alt-fields as part of a command line call for CxFlow in project mode, if a customer uses System.Tags for additional meta data, the following error is returned.
--alt-fields="System.Tags:SCA"
[11:37 AM] customer
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"$id":"1","innerException":null,"message":"VS403691: Update to work item -1 had two or more updates for field with reference name 'System.Tags'. A field cannot be updated more than once in the same update.","typeName":"System.InvalidOperationException, mscorlib","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}"
Per the documentation, these tags fields should be allowed for customer project tags in ADO but seem like They are already in use via Cxflow

 CXFLW-966 CxFlow: using System.Tags as an --alt-fields option throws an error

---

docs/Bug-Trackers-and-Feedback-Channels.md
docs/Tutorials.md
src/main/java/com/atlassian/jira/rest/client/internal/async/CustomAsynchronousJiraRestClientFactory.java
src/main/java/com/checkmarx/flow/config/JiraProperties.java
src/main/java/com/checkmarx/flow/service/JiraService.java

Added new Jira parameter named token-type to differentiate between token as password or PAT
```
jira:
url: <Jira on-premise url>
username: <Jira on-premise username>
token: <password/personal access token>
token-type: <PASSWORD/PAT> 
```
Note: When using Jira on-premises, a password is expected as the value in the token if the token-type is not specified.
https://github.com/checkmarx-ltd/cx-flow/issues/878

Added Support for Jira On-premise Personal Access Token

---

src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java
src/test/java/com/checkmarx/flow/custom/SarifSCAIssueTrackerTest.java

In a SARIF report, the `security-severity` field is set to `9.0` for all SCA findings, which is inconsistent with the markdown, text, and tag CVSS scores.
`map.get(key).getSeverity()` doesn't appear to be resolvable. This results in `security-severity` being set to the `DEFAULT_SEVERITY` (9.0).
The updated logic sets `security-severity` in the SARIF output as the max CVSS score such that the markdown, tags, and …

CXFLOW-1328: Set security-severity in the SARIF SCA report to match the markdown and tags fields

---

docs/Configuration.md
docs/Home.md
src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/config/GitLabProperties.java
src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/GitLabService.java
src/main/java/com/checkmarx/flow/service/RepoService.java
src/test/java/com/checkmarx/flow/cucumber/component/ast/parse/GitHubCommentsASTSteps.java

Added a new parameter of GitHub and GitLab named comment-update 
if false, will create a new comment for every scan in PR
```yaml
gitlab:
comment-update: false
```
```yaml
github:
comment-update: false
```
https://github.com/checkmarx-ltd/cx-flow/issues/1120
tested on GitHub and GitLab

Added new parameter  commentUpdate

---

Dockerfile
build-11.gradle
build.gradle
docs/CxSCA-Integration.md
src/main/java/com/checkmarx/flow/service/ScaConfigurationOverrider.java

Added new parameters for SCA for project tags and scan tags.
```yaml
sca:
project-tags: "k1:k2,dev"
scan-tags: "s1:s2,prod"
```
also added cx.config parameter 
```
"projectTags": "k1:k2,dev",
"scanTags": "s1:s2,prod,p1:p2"
```
Tested on SCA and ScaResolver with CLI and WebHook mode.

added scan and project tags for SCA

---

src/main/resources/logback-spring.xml

Add mask patterns for two cases where GitHub personal access tokens can appear in the CxFlow log:
- When logging HTTP headers
- When logging URLs (https://<pat>@github.com/...)
When DEBUG logging is enabled, both the Authorization header and URLs may be logged (depending on for which packages DEBUG logging is …

Mask GitHub personal access tokens in logs

---

build.gradle

For More Details : Please refer SF case : 00196418
Hi Team, we use CxFlow to runs scans in our gitlab pipelines and send the results to Jira - PFA our CI template.
We have previously tried to filter out dev, test & indirect dependencies as we do not require these to have issues raised in Jira, but it is not working - see lines 114 & 115 in the attached template.
In the CxFlow documentation, the only relevant thing I have found is here https://github.com/checkmarx-ltd/cx-flow/wiki/CxSCA-Integration#adding-the-cxsca-configuration . But it's not clear if I can filter out dev & test dependencies as well. Please can you suggest how we can prevent dev, test & indirect dependencies having Jira issues?

filter dev, test & indirect dependencies not working

---

src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
src/main/resources/logback-spring.xml

Fixed token leaks for GitLab Issues and also masked token values for SCM GitLab, ADO, Bitbucket
https://github.com/checkmarx-ltd/cx-flow/issues/1341
Tested for SCM GitHub GitLab ADO and Bitbucket

Fixed token leaks

---

build.gradle
docs/Configuration.md
docs/Proxy-and-HTTPS-Configuration.md
src/main/java/com/checkmarx/flow/config/FlowConfig.java

Adding a self-sign certificate SSL bypass in CXFlow requires careful consideration, as this process involves security implications. CXFlow is a framework designed to simplify the orchestration of various CI/CD tools and processes, and ensuring secure communication within the system is crucial. However, there are scenarios where you might need to bypass SSL verification, such as during testing or when dealing with self-signed certificates in a development environment. This guide will walk you through the necessary steps to add a self-sign certificate SSL bypass in CXFlow.
Understanding SSL Verification
SSL (Secure Socket Layer) is a standard security protocol for establishing encrypted links between a web server and a browser in an online communication. It ensures that all data passed …

CXFLW-1235 Adding code for self-sign certificate SSL bypass

---

src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
src/main/java/com/checkmarx/flow/service/FlowService.java
src/main/java/com/checkmarx/flow/service/GitHubService.java

this case is it was not LB issue API was failing due to wrong user or user expired issue due to which PR was stuck once you resumed user it started working fine.
cxflow is not showing error when api connection is failed.

CXFLW-1223 Added code for prscans-not-triggered

---

docs/Configuration.md
src/main/java/com/checkmarx/flow/config/RepoProperties.java
src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
src/main/java/com/checkmarx/flow/utils/HTMLHelper.java

A new configuration `zero-vulnerability-summary: true` has been added for all SCM. The default setting value is false. 
If the configuration is true, check if all vulnerabilities count. If everything is 0, add the comment "No SAST Vulnerability Found!!" or "No SCA Vulnerability Found!!" based on the vulnerability scanner instead for complete PR decorating to reduce PR messages. 
Tested with SAST and SCA for GITLAB and GITHUB pull request

Reduce PR decoration changes with configuration

---

src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/config/RepoProperties.java
src/main/java/com/checkmarx/flow/service/RepoService.java

Pull Decoration will be updated and refreshed according to parameter `comment-update`. Default is true. hence normally comment will get updated and if false. new comment will get added.
```
GitHub:
comment-update : false
```
https://github.com/checkmarx-ltd/cx-flow/issues/1172
tested on GitHub using SAST

Pull decoration refresh and updated

---

docs/Bug-Trackers-and-Feedback-Channels.md
docs/Configuration.md
src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/config/GitLabProperties.java
src/main/java/com/checkmarx/flow/custom/GitHubIssueTracker.java
src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java
src/main/java/com/checkmarx/flow/dto/LabelField.java

Added new parameters for GitHub and GitLab 
```yaml
fields:
- type: result
name: application
- type: result
name: project
```
Every value mentioned in fields will be added in Labels.
* **type**
* **cx-scan**: Used to map specific Checkmarx Scan Custom Field values
* **cx-sca**: Used to map specific Checkmarx SCA Scan tags values
* **static**: Used for static values (specifically requires a default-value to be provided)
* **result**: Used to map known values from Checkmarx results or repository/scan request details.  Refer to the Result values below.
* **name**: If cx-scan or cx-sca reflects the type, it is the name of the custom field within Checkmarx SAST or key of tag in case o SCA
* **default-value** Static value if no value can be determined for the respective field (Optional)
* If …

Added mapping labels capability like Jira

---

docs/Tutorials.md

Hello team,
Following your document:
https://github.com/checkmarx-ltd/cx-flow/wiki/Tutorials#cicd-variables
It seems it is possible to use a bug tracker type "GitLabDashboard"
And there are many places which mention "GitLabDasboard"
- if: '$CX_FLOW_BUG_TRACKER == "GitLabDashboard" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
However, in the code, we can see only those:
public class BugTracker {
private Type type;
public enum Type {
JIRA("JIRA"),
BITBUCKETCOMMIT("BITBUCKETCOMMIT"),
BITBUCKETPULL("BITBUCKETPULL"),
BITBUCKETSERVERPULL("BITBUCKETSERVERPULL"),
bitbucketserverpull("bitbucketserverpull"),
ADOPULL("ADOPULL"),
adopull("adopull"),
GITHUBPULL("GITHUBPULL"),
githubpull("githubpull"),
GITHUBCOMMIT("GITHUBCOMMIT"),
GITLABCOMMIT("GITLABCOMMIT"),
GITLABMERGE("GITLABMERGE"), …

pr-CXFLW-1296 Improved documentation for GitLab dashboard.

---

docs/Configuration.md
src/main/java/com/checkmarx/flow/config/SarifProperties.java
src/main/java/com/checkmarx/flow/custom/SarifIssueTracker.java

Describe the problem
The specification has a snippet in the Location object for the affected lines of code, but the Sarif output uses the Location -> message property instead.
Proposed solution
Use the Location -> region -> snippet for the affected code.
Additional details
CxFlow 1.6.40-11

CXFLW-1336 Added code to add snippet in cxflow SARIF report its configurable.

---

docs/Configuration.md

Hi
I've integrated the default gitlab ci template in my project (https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v3/Checkmarx.gitlab-ci.yml).
I have a branch develop and feature branch under a merge request.
The default gitlab ci template hase created two project:
A myrepo-develop project
A myrepo-feature-branch.
So I was wondering if it is this normal and if this two project consumes two licenses ?
I've read the wiki but it is a bit overwhelhming there's a lot of settings and it's not clear.

CXFLW-1295 Updated documentation regarding branched project

---

docs/Frequently-Asked-Questions.md
docs/cxflow_gitlab_scan_issue.md

Customer:
Sicredi
Description:
https://checkmarx.lightning.force.com/lightning/r/Case/5004K00000A25NeQAJ/view 
The MR comment is shown to be created by the owner of the Repo and not by the user who created the MR. It should be either the user who created the MR or just a generic Checkmarx user (if possible).
Actual Result:
The user who created the repo is the user added in the MR comment in GitLab.
Expected Result:
The user who create the MR is the user added in the GitLab comment.
The user has permission to add comments in GitLab. We need to add this information to the documentation.

CXFLW-857 Added code for gitlab user

---

build.gradle
docs/Configuration.md
src/main/java/com/checkmarx/flow/config/FlowProperties.java
src/main/java/com/checkmarx/flow/config/GitHubProperties.java
src/main/java/com/checkmarx/flow/controller/GitHubController.java
src/main/java/com/checkmarx/flow/dto/github/Comment.java
src/main/java/com/checkmarx/flow/dto/github/CommentEvent.java
src/main/java/com/checkmarx/flow/dto/github/CxFlowCommandHandler.java
src/main/java/com/checkmarx/flow/dto/github/CxFlowCommandParser.java
src/main/java/com/checkmarx/flow/dto/github/EventCommon.java
src/main/java/com/checkmarx/flow/dto/github/Issue.java
src/main/java/com/checkmarx/flow/dto/github/Reactions.java
src/main/java/com/checkmarx/flow/dto/github/issue/Issue.java
src/main/java/com/checkmarx/flow/dto/github/issue/SubIssuesSummary.java
src/main/java/com/checkmarx/flow/service/AbstractVulnerabilityScanner.java
src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
src/main/java/com/checkmarx/flow/service/GitHubService.java
src/main/java/com/checkmarx/flow/service/RepoService.java
src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java

Description
Description & Value:
The goal is for users to be able to inquire about what CXFlow is doing by commenting with @CxFlow in their respective bug tracker. CXFlow would then capture these events and interpret the command in the comment (e.g., update, rescan, or other actions). For unsupported commands like "open the pod bay doors" (an impossible command for CXFlow), the system would respond with, "I'm afraid I can't do that, Dave."
Background:
In a PR the developer is waiting for a scan and sometimes would like to get some information or take some actions with CxFlow.
User Flow:
Recording: [link](https://checkmarx-my.sharepoint.com/personal/fatima_goncalves_checkmarx_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Ffatima%5Fgoncalves%5Fcheckmarx%5Fcom%2FDocuments%2FRecordings%2F%5BCxFl …

CXFLW-1520 GH | PR decoration comments interacting with CxFlow

---

src/main/java/com/checkmarx/flow/config/FlowProperties.java
src/main/java/com/checkmarx/flow/service/ResultsService.java

Description
Since version 1.7.01, when passing argument --gitlab.scan-submitted-comment="false", instead of only disabling the MR comment that says "Scan submitted to checkmarx", it also disable the comment containing the scan summary. This contradicts the documentation and makes it impossible to only disable the scan submitted comment. This is caused by this if that was added in ResultsService in version 1.7.01:
case GITLABMERGE:
if (gitLabService.isScanSubmittedComment() && request.getScanSubmittedComment()) {
gitLabService.processMerge(request, results);
gitLabService.endBlockMerge(request);
}
Expected Behavior
When scan-submitted-comment is set to false, cxflow should still add the scan summary as a merge request comment but should not comment to say that a scan was submitted to …

CXFLW-1590 Fixed issue for Pr feedback false

---

build.gradle
docs/Delete-Branch.md
src/main/java/com/checkmarx/flow/service/ASTScanner.java
src/main/java/com/checkmarx/flow/service/AbstractASTScanner.java
src/main/java/com/checkmarx/flow/service/FlowService.java
src/main/java/com/checkmarx/flow/service/ProjectNameGenerator.java
src/main/java/com/checkmarx/flow/service/SCAScanner.java
src/main/java/com/checkmarx/flow/service/SastScanner.java
src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java

made changes required for deleting project while using webhook delete event for CxSCA projects

Added logic for deleting CxSCA project

---

build.gradle
docs/Execution.md
src/main/java/com/checkmarx/flow/CxFlowRunner.java
src/main/java/com/checkmarx/flow/service/VulnerabilityScanner.java

Added two CLI parameter `--delete` and `--delete-project` where `--delete` is standalone parameter if want to use only to delete project and `--delete-project ` can be used with --scan or --project or --batch.
https://github.com/checkmarx-ltd/cx-flow/issues/734

Project deletion support via CLI command
